### ISSUE TITLE
load project fails for pages which have not been defined (Trac #978)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1051]
To reproduce:

* load the test/1d_data/latex_smeared.xml, 
* send to fitting, 
* fit the first dataset to a sphere model (start radius at 2000), 
* do not touch the second fit page
* save project
* restart sasview
* load project

```text
18:54:06 - ERROR : sas.sasgui.guiframe.gui_statusbar:  80: 2017-06-19 18:54:06 : Error: This model state has missing or outdated information.
Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/fitpage.py", line 2028, in reset_page
    self.reset_page_helper(state)
  File "/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/basepage.py", line 1160, in reset_page_helper
    state._convert_to_sasmodels()
  File "/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/pagestate.py", line 477, in _convert_to_sasmodels
    self._old_first_model()
  File "/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/pagestate.py", line 401, in _old_first_model
    self.formfactorcombobox = FIRST_FORM[self.categorycombobox]
KeyError: 'Cylinder'
```

Saved project file is attached

Migrated from http://trac.sasview.org/ticket/978
```json
{
    "status": "closed",
    "changetime": "2017-09-21T14:16:57",
    "_ts": "2017-09-21 14:16:57.111148+00:00",
    "description": "To reproduce:\n\n* load the test/1d_data/latex_smeared.xml, \n* send to fitting, \n* fit the first dataset to a sphere model (start radius at 2000), \n* do not touch the second fit page\n* save project\n* restart sasview\n* load project\n\n{{{\n18:54:06 - ERROR : sas.sasgui.guiframe.gui_statusbar:  80: 2017-06-19 18:54:06 : Error: This model state has missing or outdated information.\nTraceback (most recent call last):\n  File \"/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/fitpage.py\", line 2028, in reset_page\n    self.reset_page_helper(state)\n  File \"/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/basepage.py\", line 1160, in reset_page_helper\n    state._convert_to_sasmodels()\n  File \"/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/pagestate.py\", line 477, in _convert_to_sasmodels\n    self._old_first_model()\n  File \"/Users/pkienzle/Source/sasview-new/src/sas/sasgui/perspectives/fitting/pagestate.py\", line 401, in _old_first_model\n    self.formfactorcombobox = FIRST_FORM[self.categorycombobox]\nKeyError: 'Cylinder'\n}}}\n\nSaved project file is attached",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-06-19T22:59:17",
    "component": "SasView",
    "summary": "load project fails for pages which have not been defined",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/06/19 22:59:53`: **pkienzle** changed attachment from "" to "_latex_fit_report.svs"

**Comment by butlerpd** [comment]
Trac update at `2017/09/21 14:16:57`: 
* **butler** commented:

fixed by PR 94


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
