### ISSUE TITLE
Order of combining P(Q) and S(Q) in Plugins seems to matter (Trac #1035)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1102]
First noticed by Sarah Rogers, verified by smk78.

This plugin will compile and appear to work:

```text
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('ellipsoid+ellipsoid@hardsphere')
model_info.name = 'Take Two'
model_info.description = 'Ellipse + Ellipse * HS'
Model = make_model_from_info(model_info)
```

but this will not:

```text
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('ellipsoid@hardsphere+ellipsoid')
model_info.name = 'Take Four'
model_info.description = 'Ellipse * HS + Ellipse'
Model = make_model_from_info(model_info)
```

Note the order of combining the P(Q)s and S(Q)s.

A .pyc is created in both cases but only the first plugin appears in the Fit Page plugin model category drop down. However both appear in the Advanced Plugin Model Editor drop down. If you select the second plugin in that and Run to compile the model you get this traceback:

```text
Running model 'takefour.py'...

Error occurred:
Traceback (most recent call last):
  File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 53, in show_model_output
  File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 32, in check_model
  File "sasmodels\sasview_model.pyc", line 111, in load_custom_model
  File "sasmodels\custom\__init__.pyc", line 45, in load_custom_kernel_module
  File "sasmodels\custom\__init__.pyc", line 36, in load_module_from_path
  File "C:\Users\loq\.sasview\plugin_models\takefour.py", line 5, in <module>
  File "sasmodels\core.pyc", line 154, in load_model_info
  File "sasmodels\product.pyc", line 50, in make_product_info
TypeError: S needs radius_effective as first parameter
```

Now, interestingly, the first plugin (the one that does load in the Fit Page) only has the volfraction parameter from the hardsphere S(Q). The radius_effective parameter is missing.

'''So there are two questions:'''

'''1) Is the apparent dependence on the order of combining the P(Q)s and S(Q)s a design feature or a bug?'''

'''2) Why isn't the radius_effective parameter passed to the Fit Page?'''

But it gets more interesting. If you create this:

```text
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('ellipsoid*hardsphere')
model_info.name = 'ellipstimesHS'
model_info.description = 'Ellipse * HS'
Model = make_model_from_info(model_info)
```

and then this:

```text
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('ellipsoid+custom.ellipstimesHS')
model_info.name = 'Take Three'
model_info.description = 'Ellipse + Ellipse * HS'
Model = make_model_from_info(model_info)
```

It appears in the Fit Page model category drop down (like the first plugin above) but ''does'' contain the radius_effective parameter (unlike the first plugin above)!

'''Final question:'''

'''3) Which of these should be giving a model of [ (ellipsoid) + (ellipsoid * S(Q)) ]?'''

Migrated from http://trac.sasview.org/ticket/1035
```json
{
    "status": "closed",
    "changetime": "2018-02-13T16:55:09",
    "_ts": "2018-02-13 16:55:09.137815+00:00",
    "description": "First noticed by Sarah Rogers, verified by smk78.\n\nThis plugin will compile and appear to work:\n\n{{{\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('ellipsoid+ellipsoid@hardsphere')\nmodel_info.name = 'Take Two'\nmodel_info.description = 'Ellipse + Ellipse * HS'\nModel = make_model_from_info(model_info)\n}}}\n\nbut this will not:\n\n{{{\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('ellipsoid@hardsphere+ellipsoid')\nmodel_info.name = 'Take Four'\nmodel_info.description = 'Ellipse * HS + Ellipse'\nModel = make_model_from_info(model_info)\n}}}\n\nNote the order of combining the P(Q)s and S(Q)s.\n\nA .pyc is created in both cases but only the first plugin appears in the Fit Page plugin model category drop down. However both appear in the Advanced Plugin Model Editor drop down. If you select the second plugin in that and Run to compile the model you get this traceback:\n\n{{{\nRunning model 'takefour.py'...\n\nError occurred:\nTraceback (most recent call last):\n  File \"sas\\sasgui\\perspectives\\calculator\\pyconsole.pyc\", line 53, in show_model_output\n  File \"sas\\sasgui\\perspectives\\calculator\\pyconsole.pyc\", line 32, in check_model\n  File \"sasmodels\\sasview_model.pyc\", line 111, in load_custom_model\n  File \"sasmodels\\custom\\__init__.pyc\", line 45, in load_custom_kernel_module\n  File \"sasmodels\\custom\\__init__.pyc\", line 36, in load_module_from_path\n  File \"C:\\Users\\loq\\.sasview\\plugin_models\\takefour.py\", line 5, in <module>\n  File \"sasmodels\\core.pyc\", line 154, in load_model_info\n  File \"sasmodels\\product.pyc\", line 50, in make_product_info\nTypeError: S needs radius_effective as first parameter\n}}}\n\nNow, interestingly, the first plugin (the one that does load in the Fit Page) only has the volfraction parameter from the hardsphere S(Q). The radius_effective parameter is missing.\n\n'''So there are two questions:'''\n\n'''1) Is the apparent dependence on the order of combining the P(Q)s and S(Q)s a design feature or a bug?'''\n\n'''2) Why isn't the radius_effective parameter passed to the Fit Page?'''\n\nBut it gets more interesting. If you create this:\n\n{{{\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('ellipsoid*hardsphere')\nmodel_info.name = 'ellipstimesHS'\nmodel_info.description = 'Ellipse * HS'\nModel = make_model_from_info(model_info)\n}}}\n\nand then this:\n\n{{{\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('ellipsoid+custom.ellipstimesHS')\nmodel_info.name = 'Take Three'\nmodel_info.description = 'Ellipse + Ellipse * HS'\nModel = make_model_from_info(model_info)\n}}}\n\nIt appears in the Fit Page model category drop down (like the first plugin above) but ''does'' contain the radius_effective parameter (unlike the first plugin above)!\n\n'''Final question:'''\n\n'''3) Which of these should be giving a model of [ (ellipsoid) + (ellipsoid * S(Q)) ]?'''\n\n\n\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-11-14T16:37:05",
    "component": "SasView",
    "summary": "Order of combining P(Q) and S(Q) in Plugins seems to matter",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "awashington",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2017/11/14 16:39:08`: 
* **smk78** changed attachment from "" to "takethree.png"
* **smk78** commented:

Screenshot of different plugin examples

**Comment by smk78** [comment]
Trac update at `2017/11/14 16:46:15`: **smk78** commented:

Forgot to add. This was using Jenkins Win 7 4.2.0 Build 803

**Comment by pkienzle** [comment]
Trac update at `2017/11/22 17:45:47`: **pkienzle** commented:

sasmodels.core.load_model_info is first splitting on '@' then splitting on '+' which gives the wrong precedence.  Need to rearrange the function so that the '@' split happens after '+'.

**Comment by butlerpd** [comment]
Trac update at `2018/01/09 15:11:18`: 
* **butler** changed owner from "" to "awashington"
* **butler** changed status from "new" to "assigned"

**Comment by rprospero** [comment]
Trac update at `2018/01/23 15:26:19`: 
* **awashington** changed _comment0 from "Pull requests #60 and #61 have both been offered as competing solutions to the problem." to "1516721200067691"
* **awashington** commented:

Pull requests 60 and 61 have both been offered as competing solutions to the problem.

**Comment by butlerpd** [comment]
Trac update at `2018/02/04 17:46:39`: 
* **butler** commented:

was not closed with merge of pull request so closing manually


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"

**Comment by smk78** [comment]
Trac update at `2018/02/13 16:55:09`: **smk78** commented:

Have checked awashington's fix by pulling from master on 13/02/2018 10:30 and building locally. Looks good to me!
