### ISSUE TITLE
Can't use a user-created plugin model in a plugin model (Trac #1052)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1110]
Tested with Jenkins nightly and pulling from master and building, both on Win7.

I did have a quick look to see if this was already ticketed but couldn't see anything obvious, so apologies if I've missed an existing ticket.

You can create a plugin using Sum|Multi to, say, add two built-in functions together. If you then want to add a third function to those two the natural reaction of a normal user (eg, one of our team members) is to go back to Sum|Multi and create a new plugin selecting the previously created plugin as one of the two functions.

If you do this !SasView creates a syntactically-correct and valid-looking .py, for example:

```text
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('sarah2+sphere')
model_info.name = 'sarah5'
Model = make_model_from_info(model_info)
```

but the new plugin does not appear in the model chooser. If you go the Advanced Model Editor, select the new plugin and run Check Model you get something like this (where sarah2 was the first plugin created):

```text
Running model 'sarah5.py'...

Error occurred:
Traceback (most recent call last):
  File "D:\!SasViewDevelopment\sasview\src\sas\sasgui\perspectives\calculator\pyconsole.py", line 53, in show_model_output
    result, errmsg = check_model(fname), None
  File "D:\!SasViewDevelopment\sasview\src\sas\sasgui\perspectives\calculator\pyconsole.py", line 32, in check_model
    Model = load_custom_model(path)
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\sasview_model.py", line 114, in load_custom_model
    kernel_module = custom.load_custom_kernel_module(path)
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\custom\__init__.py", line 45, in load_custom_kernel_module
    os.path.expanduser(path))
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\custom\__init__.py", line 36, in load_module_from_path
    module = imp.load_source(fullname, os.path.expanduser(path))
  File "C:\Users\smk78\.sasview\plugin_models\sarah5.py", line 5, in <module>
    model_info = load_model_info('sphere+sarah2')
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\core.py", line 162, in load_model_info
    addition_parts = [load_model_info(part) for part in addition_parts_names]
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\core.py", line 182, in load_model_info
    kernel_module = generate.load_kernel_module(product_parts_names[0])
  File "D:\!SasViewDevelopment\sasmodels\sasmodels\generate.py", line 837, in load_kernel_module
    __import__('sasmodels.models.'+model_name)
!ImportError: No module named sarah2
```

The workaround is simply to edit the plugin directly and specify all three functions in one plugin, for example:

```text

from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('elliptical_cylinder+broad_peak+sphere')
model_info.name = 'sarah4'
Model = make_model_from_info(model_info)
```

but this is surely not we intended or would prefer?

Am marking this as a blocker for now so it gets some visibility/discussion, but fully expect it to be dropped a notch later.

Migrated from http://trac.sasview.org/ticket/1052
```json
{
    "status": "closed",
    "changetime": "2018-03-18T18:37:30",
    "_ts": "2018-03-18 18:37:30.088309+00:00",
    "description": "Tested with Jenkins nightly and pulling from master and building, both on Win7.\n\nI did have a quick look to see if this was already ticketed but couldn't see anything obvious, so apologies if I've missed an existing ticket.\n\nYou can create a plugin using Sum|Multi to, say, add two built-in functions together. If you then want to add a third function to those two the natural reaction of a normal user (eg, one of our team members) is to go back to Sum|Multi and create a new plugin selecting the previously created plugin as one of the two functions.\n\nIf you do this !SasView creates a syntactically-correct and valid-looking .py, for example:\n\n{{{\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('sarah2+sphere')\nmodel_info.name = 'sarah5'\nModel = make_model_from_info(model_info)\n}}}\n\nbut the new plugin does not appear in the model chooser. If you go the Advanced Model Editor, select the new plugin and run Check Model you get something like this (where sarah2 was the first plugin created):\n\n{{{\nRunning model 'sarah5.py'...\n\nError occurred:\nTraceback (most recent call last):\n  File \"D:\\!SasViewDevelopment\\sasview\\src\\sas\\sasgui\\perspectives\\calculator\\pyconsole.py\", line 53, in show_model_output\n    result, errmsg = check_model(fname), None\n  File \"D:\\!SasViewDevelopment\\sasview\\src\\sas\\sasgui\\perspectives\\calculator\\pyconsole.py\", line 32, in check_model\n    Model = load_custom_model(path)\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\sasview_model.py\", line 114, in load_custom_model\n    kernel_module = custom.load_custom_kernel_module(path)\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\custom\\__init__.py\", line 45, in load_custom_kernel_module\n    os.path.expanduser(path))\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\custom\\__init__.py\", line 36, in load_module_from_path\n    module = imp.load_source(fullname, os.path.expanduser(path))\n  File \"C:\\Users\\smk78\\.sasview\\plugin_models\\sarah5.py\", line 5, in <module>\n    model_info = load_model_info('sphere+sarah2')\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\core.py\", line 162, in load_model_info\n    addition_parts = [load_model_info(part) for part in addition_parts_names]\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\core.py\", line 182, in load_model_info\n    kernel_module = generate.load_kernel_module(product_parts_names[0])\n  File \"D:\\!SasViewDevelopment\\sasmodels\\sasmodels\\generate.py\", line 837, in load_kernel_module\n    __import__('sasmodels.models.'+model_name)\n!ImportError: No module named sarah2\n}}}\n\nThe workaround is simply to edit the plugin directly and specify all three functions in one plugin, for example:\n\n{{{\n\nfrom sasmodels.core import load_model_info\nfrom sasmodels.sasview_model import make_model_from_info\n\nmodel_info = load_model_info('elliptical_cylinder+broad_peak+sphere')\nmodel_info.name = 'sarah4'\nModel = make_model_from_info(model_info)\n}}}\n\nbut this is surely not we intended or would prefer?\n\nAm marking this as a blocker for now so it gets some visibility/discussion, but fully expect it to be dropped a notch later.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-12-18T17:16:35",
    "component": "SasView",
    "summary": "Can't use a user-created plugin model in a plugin model",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/01/23 01:45:54`: **butler** commented:

So is this because the generate infrastructure only looks in the built in model directory and not the plugin directory?

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 15:21:00`: 
* **butler** commented:

See if we can get PK hack in quickly.


* **butler** changed owner from "" to "krzywon"
* **butler** changed priority from "blocker" to "critical"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2018/03/14 11:22:04`: **smk78** commented:

Have tested the fix in krzywon's sasmodels/sasview ticket-1052 branches. Works for me (on W10)! Recommend the PRs be merged.
