### ISSUE TITLE
py3 support for 4.x series (Trac #1233)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1260]
!SasView 4.3 will run on python 3.x with wx 4.x, but it hasn't been extensively tested.  Need to test that the various dialogs function correctly, and make sure that file I/O works.

Here's a list of file open calls in the code:

```text
$ grep -r "\\bopen[(]" src | grep -v [.]open | grep py:
src/examples/data_generator/testdata_generator.py:        fd = open(filename, 'w')
src/sas/_config.py:    if not "SAS_OPENCL" in open(path).read():
src/sas/_config.py:            open(config_file, "a+").write("SAS_OPENCL = \"None\"\n")
src/sas/sasgui/perspectives/invariant/report_dialog.py:            f = open(fName, 'w')
src/sas/sasgui/perspectives/invariant/report_dialog.py:        f = open(fName, 'w')
src/sas/sasgui/perspectives/invariant/invariant_state.py:        html_template = open(path_report_html, "r")
src/sas/sasgui/perspectives/invariant/invariant_state.py:            fd = open('test000', 'w')
src/sas/sasgui/perspectives/invariant/invariant_state.py:            fd = open(filename, 'w')
src/sas/sasgui/perspectives/fitting/basepage.py:            input_f = open(path, 'r')
src/sas/sasgui/perspectives/fitting/basepage.py:        with open(categorization_file, 'rb') as f:
src/sas/sasgui/perspectives/fitting/report_dialog.py:            with open(filename, 'w') as f:
src/sas/sasgui/perspectives/fitting/report_dialog.py:            with open(filename, 'w') as f:
src/sas/sasgui/perspectives/calculator/resolution_calculator_panel.py:            input_f = open(path, 'r')
src/sas/sasgui/perspectives/calculator/model_editor.py:        with open(self.fname, 'w') as out_f:
src/sas/sasgui/perspectives/calculator/model_editor.py:        out_f = open(fname, 'w')
src/sas/sasgui/perspectives/pr/inversion_state.py:            fd = open(file, 'w')
src/sas/sasgui/perspectives/pr/inversion_state.py:            fd = open(filename, 'w')
src/sas/sasgui/perspectives/pr/pr.py:            input_f = open(path, 'r')
src/sas/sasgui/perspectives/pr/pr.py:            input_f = open(path, 'r')
src/sas/sasgui/perspectives/corfunc/corfunc_state.py:            fd = open(filename, 'w')
src/sas/sasgui/perspectives/corfunc/corfunc_state.py:        fd = open(filename, 'w')
src/sas/sasgui/perspectives/file_converter/converter_panel.py:            f = open(filename, 'r')
src/sas/sasgui/guiframe/config.py:            out = open(__EVT_DEBUG_FILENAME__, 'a')
src/sas/sasgui/guiframe/report_dialog.py:            resultFile = open(filename, "w+b")
src/sas/sasgui/guiframe/startup_configuration.py:        with open(path, 'w') as out_f:
src/sas/sasgui/guiframe/CategoryInstaller.py:            with open(serialized_file, 'rb') as f:
src/sas/sasgui/guiframe/CategoryInstaller.py:            json.dump(master_category_dict, open(serialized_file, 'wb'))
src/sas/sasgui/guiframe/CategoryManager.py:        cat_file = open(CategoryInstaller.get_user_file(), 'wb')
src/sas/sasgui/guiframe/CategoryManager.py:                with open(cat_file, 'rb') as f:
src/sas/sasgui/guiframe/gui_manager.py:        fd = open(file_name, 'r')
src/sas/sasgui/guiframe/gui_manager.py:            fd = open(file_name, 'w')
src/sas/sasgui/guiframe/gui_manager.py:            fd = open(temp_file_name, 'w')
src/sas/sasgui/guiframe/gui_manager.py:                fd = open(fName, 'w')
src/sas/sasgui/guiframe/gui_manager.py:            config_file = open(custom_config.__file__)
src/sas/sasgui/guiframe/gui_manager.py:            new_config_file = open(custom_config.__file__,"w")
src/sas/sasgui/guiframe/gui_manager.py:            out = open(path, 'w')
src/sas/sasview/local_config.py:            out = open(__EVT_DEBUG_FILENAME__, 'a')
src/sas/sascalc/calculator/sas_gen.py:            input_f = open(path, 'rb')
src/sas/sascalc/calculator/sas_gen.py:            input_f = open(path, 'rb')
src/sas/sascalc/calculator/sas_gen.py:                input_f = open(path, 'rb')
src/sas/sascalc/calculator/sas_gen.py:        out = open(path, 'w')
src/sas/sascalc/fit/models.py:    out = open(PLUGIN_LOG, 'a')
src/sas/sascalc/fit/Loader.py:            input_f =  open(self.filename, 'r')
src/sas/sascalc/fit/pagestate.py:            fd = open(file, 'w')
src/sas/sascalc/fit/pagestate.py:        fd = open(filename, 'w')
src/sas/sascalc/pr/fit/Loader.py:            input_f =  open(self.filename, 'r')
src/sas/sascalc/pr/num_term.py:        input_f = open(path, 'r')
src/sas/sascalc/pr/invertor.py:        file = open(path, 'w')
src/sas/sascalc/pr/invertor.py:                fd = open(path, 'r')
src/sas/sascalc/file_converter/bsl_loader.py:        header_file = open(filename, 'r')
src/sas/sascalc/file_converter/otoko_loader.py:        with open(header_path, "r") as header_file:
src/sas/sascalc/file_converter/otoko_loader.py:            with open(info.file_path, "rb") as binary_file:
src/sas/sascalc/file_converter/cansas_writer.py:        file_ref = open(filename, 'w')
src/sas/sascalc/file_converter/ascii2d_loader.py:        with open(self.data_path, 'r') as file_handle:
src/sas/sascalc/file_converter/red2d_writer.py:        fd = open(filename, 'w')
src/sas/sascalc/dataloader/file_reader_base_class.py:                    self.f_open = open(filepath, 'rb')
src/sas/sascalc/dataloader/readers/cansas_reader.py:        file_ref = open(filename, 'wb')
src/sas/sascalc/dataloader/readers/red2d_reader.py:            fd = open(filename, 'w')
```

Migrated from http://trac.sasview.org/ticket/1233
```json
{
    "status": "new",
    "changetime": "2019-02-22T19:01:30",
    "_ts": "2019-02-22 19:01:30.270298+00:00",
    "description": "!SasView 4.3 will run on python 3.x with wx 4.x, but it hasn't been extensively tested.  Need to test that the various dialogs function correctly, and make sure that file I/O works.\n\nHere's a list of file open calls in the code:\n{{{\n$ grep -r \"\\\\bopen[(]\" src | grep -v [.]open | grep py:\nsrc/examples/data_generator/testdata_generator.py:        fd = open(filename, 'w')\nsrc/sas/_config.py:    if not \"SAS_OPENCL\" in open(path).read():\nsrc/sas/_config.py:            open(config_file, \"a+\").write(\"SAS_OPENCL = \\\"None\\\"\\n\")\nsrc/sas/sasgui/perspectives/invariant/report_dialog.py:            f = open(fName, 'w')\nsrc/sas/sasgui/perspectives/invariant/report_dialog.py:        f = open(fName, 'w')\nsrc/sas/sasgui/perspectives/invariant/invariant_state.py:        html_template = open(path_report_html, \"r\")\nsrc/sas/sasgui/perspectives/invariant/invariant_state.py:            fd = open('test000', 'w')\nsrc/sas/sasgui/perspectives/invariant/invariant_state.py:            fd = open(filename, 'w')\nsrc/sas/sasgui/perspectives/fitting/basepage.py:            input_f = open(path, 'r')\nsrc/sas/sasgui/perspectives/fitting/basepage.py:        with open(categorization_file, 'rb') as f:\nsrc/sas/sasgui/perspectives/fitting/report_dialog.py:            with open(filename, 'w') as f:\nsrc/sas/sasgui/perspectives/fitting/report_dialog.py:            with open(filename, 'w') as f:\nsrc/sas/sasgui/perspectives/calculator/resolution_calculator_panel.py:            input_f = open(path, 'r')\nsrc/sas/sasgui/perspectives/calculator/model_editor.py:        with open(self.fname, 'w') as out_f:\nsrc/sas/sasgui/perspectives/calculator/model_editor.py:        out_f = open(fname, 'w')\nsrc/sas/sasgui/perspectives/pr/inversion_state.py:            fd = open(file, 'w')\nsrc/sas/sasgui/perspectives/pr/inversion_state.py:            fd = open(filename, 'w')\nsrc/sas/sasgui/perspectives/pr/pr.py:            input_f = open(path, 'r')\nsrc/sas/sasgui/perspectives/pr/pr.py:            input_f = open(path, 'r')\nsrc/sas/sasgui/perspectives/corfunc/corfunc_state.py:            fd = open(filename, 'w')\nsrc/sas/sasgui/perspectives/corfunc/corfunc_state.py:        fd = open(filename, 'w')\nsrc/sas/sasgui/perspectives/file_converter/converter_panel.py:            f = open(filename, 'r')\nsrc/sas/sasgui/guiframe/config.py:            out = open(__EVT_DEBUG_FILENAME__, 'a')\nsrc/sas/sasgui/guiframe/report_dialog.py:            resultFile = open(filename, \"w+b\")\nsrc/sas/sasgui/guiframe/startup_configuration.py:        with open(path, 'w') as out_f:\nsrc/sas/sasgui/guiframe/CategoryInstaller.py:            with open(serialized_file, 'rb') as f:\nsrc/sas/sasgui/guiframe/CategoryInstaller.py:            json.dump(master_category_dict, open(serialized_file, 'wb'))\nsrc/sas/sasgui/guiframe/CategoryManager.py:        cat_file = open(CategoryInstaller.get_user_file(), 'wb')\nsrc/sas/sasgui/guiframe/CategoryManager.py:                with open(cat_file, 'rb') as f:\nsrc/sas/sasgui/guiframe/gui_manager.py:        fd = open(file_name, 'r')\nsrc/sas/sasgui/guiframe/gui_manager.py:            fd = open(file_name, 'w')\nsrc/sas/sasgui/guiframe/gui_manager.py:            fd = open(temp_file_name, 'w')\nsrc/sas/sasgui/guiframe/gui_manager.py:                fd = open(fName, 'w')\nsrc/sas/sasgui/guiframe/gui_manager.py:            config_file = open(custom_config.__file__)\nsrc/sas/sasgui/guiframe/gui_manager.py:            new_config_file = open(custom_config.__file__,\"w\")\nsrc/sas/sasgui/guiframe/gui_manager.py:            out = open(path, 'w')\nsrc/sas/sasview/local_config.py:            out = open(__EVT_DEBUG_FILENAME__, 'a')\nsrc/sas/sascalc/calculator/sas_gen.py:            input_f = open(path, 'rb')\nsrc/sas/sascalc/calculator/sas_gen.py:            input_f = open(path, 'rb')\nsrc/sas/sascalc/calculator/sas_gen.py:                input_f = open(path, 'rb')\nsrc/sas/sascalc/calculator/sas_gen.py:        out = open(path, 'w')\nsrc/sas/sascalc/fit/models.py:    out = open(PLUGIN_LOG, 'a')\nsrc/sas/sascalc/fit/Loader.py:            input_f =  open(self.filename, 'r')\nsrc/sas/sascalc/fit/pagestate.py:            fd = open(file, 'w')\nsrc/sas/sascalc/fit/pagestate.py:        fd = open(filename, 'w')\nsrc/sas/sascalc/pr/fit/Loader.py:            input_f =  open(self.filename, 'r')\nsrc/sas/sascalc/pr/num_term.py:        input_f = open(path, 'r')\nsrc/sas/sascalc/pr/invertor.py:        file = open(path, 'w')\nsrc/sas/sascalc/pr/invertor.py:                fd = open(path, 'r')\nsrc/sas/sascalc/file_converter/bsl_loader.py:        header_file = open(filename, 'r')\nsrc/sas/sascalc/file_converter/otoko_loader.py:        with open(header_path, \"r\") as header_file:\nsrc/sas/sascalc/file_converter/otoko_loader.py:            with open(info.file_path, \"rb\") as binary_file:\nsrc/sas/sascalc/file_converter/cansas_writer.py:        file_ref = open(filename, 'w')\nsrc/sas/sascalc/file_converter/ascii2d_loader.py:        with open(self.data_path, 'r') as file_handle:\nsrc/sas/sascalc/file_converter/red2d_writer.py:        fd = open(filename, 'w')\nsrc/sas/sascalc/dataloader/file_reader_base_class.py:                    self.f_open = open(filepath, 'rb')\nsrc/sas/sascalc/dataloader/readers/cansas_reader.py:        file_ref = open(filename, 'wb')\nsrc/sas/sascalc/dataloader/readers/red2d_reader.py:            fd = open(filename, 'w')\n}}}",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView QA and testing",
    "time": "2019-02-22T19:01:30",
    "component": "SasView",
    "summary": "py3 support for 4.x series",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
advanced editor is failing:
```
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/perspectives/calculator/pyconsole.py", line 326, in OnCheckModel
    if not self._check_saved():
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/perspectives/calculator/pyconsole.py", line 341, in _check_saved
    cancel = self.bufferSuggestSave()
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/wx/py/editor.py", line 243, in bufferSuggestSave
    cancel = self.bufferSave()
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/wx/py/editor.py", line 212, in bufferSave
    self.buffer.save()
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/wx/py/buffer.py", line 91, in save
    self.doc.write(self.editor.getText())
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/wx/py/document.py", line 38, in write
    f.write(text)
TypeError: a bytes-like object is required, not 'str'
```

Could monkeypatch the following:
```
In [1]: wx.py.buffer.document.Document.write??                                                                                                                                                                 
Signature: wx.py.buffer.document.Document.write(self, text)
Source:   
    def write(self, text):
        """Write text to file."""
        try:
            f = open(self.filepath, 'wb')
            f.write(text)
        finally:
            if f:
                f.close()
File:      ~/anaconda/envs/py36/lib/python3.6/site-packages/wx/py/document.py
Type:      function
```

Reported as wxWidgets/Phoenix#1193

**Comment by butlerpd** [comment]
The pull request was merged and PK thinks it closes this ticket which he opened.  Seems reasonable to close
