### ISSUE TITLE
matplotlib has remove hold() method (Trac #1266)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1286]
sasview 4.x, recent versions of matplotlib.  Don't know if ESS gui uses hold().

With a recent matplotlib package from anaconda I get the following error:

```text
Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/plotting.py", line 326, in _on_plot_event
    new_panel = self.create_1d_panel(data, group_id)
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/plotting.py", line 197, in create_1d_panel
    ytransform=ytransform, style=wx.RAISED_BORDER)
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/Plotter1D.py", line 92, in __init__
    self.graph.render(self)
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/plottools/plottables.py", line 314, in render
    plot.clear()
  File "/Users/pkienzle/Source/sasview/src/sas/sasgui/plottools/PlotPanel.py", line 1237, in clear
    self.subplot.hold(True)
AttributeError: 'AxesSubplot' object has no attribute 'hold'
```

They did warn us it was going away eventually:

    https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hold.html

Migrated from http://trac.sasview.org/ticket/1266
```json
{
    "status": "new",
    "changetime": "2019-03-29T16:04:07",
    "_ts": "2019-03-29 16:04:07.007221+00:00",
    "description": "sasview 4.x, recent versions of matplotlib.  Don't know if ESS gui uses hold().\n\nWith a recent matplotlib package from anaconda I get the following error:\n{{{\nTraceback (most recent call last):\n  File \"/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/plotting.py\", line 326, in _on_plot_event\n    new_panel = self.create_1d_panel(data, group_id)\n  File \"/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/plotting.py\", line 197, in create_1d_panel\n    ytransform=ytransform, style=wx.RAISED_BORDER)\n  File \"/Users/pkienzle/Source/sasview/src/sas/sasgui/guiframe/local_perspectives/plotting/Plotter1D.py\", line 92, in __init__\n    self.graph.render(self)\n  File \"/Users/pkienzle/Source/sasview/src/sas/sasgui/plottools/plottables.py\", line 314, in render\n    plot.clear()\n  File \"/Users/pkienzle/Source/sasview/src/sas/sasgui/plottools/PlotPanel.py\", line 1237, in clear\n    self.subplot.hold(True)\nAttributeError: 'AxesSubplot' object has no attribute 'hold'\n}}}\n\nThey did warn us it was going away eventually:\n\n    https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hold.html",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2019-03-29T13:38:31",
    "component": "SasView",
    "summary": "matplotlib has remove hold() method",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
@pkienzle believes the recently merged PR (#211) fixes this issue. Since he initiated the ticket will assume he has verified that the hold error is no longer generated, so will close.  Question unresolved is how this affects 5.x series.  Testing of newly released 5.0 and future release should reveal any errors.
