### ISSUE TITLE
5.0 plugin product model error ?

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1301]
In my local build of 5.0, ESS_GUI, I made a plugin model for  sphere times hardsphere

This does not work - likely a feature not yet coded - see error message below.

ALSO need to decide how we handle the beta(Q) options,  structure_factor_mode, radius_effective_mode etc.

15:43:17 - INFO: 2019-04-10 15:43:17
15:43:17 - ERROR: Traceback (most recent call last):
  File "C:\sasview42\sasview\src\sas\sascalc\data_util\calcthread.py", line 274, in _run
    self.compute(*args, **kwargs)
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\ModelThread.py", line 211, in compute
    intermediate_results = intermediate_results()
TypeError: 'list' object is not callable

**Comment by pkienzle** [comment]
Please upload the model file.  You should be able to do upload it as a [gist](https://gist.github.com/), and link to it from an issue or PR.

**Comment by RichardHeenan** [comment]
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('sphere*hardsphere')
model_info.name = 'sphere_HSSQ'
model_info.description = '5.0 sphere @ hardsphere'
Model = make_model_from_info(model_info)

**Comment by RichardHeenan** [comment]
try here ?

https://gist.github.com/RichardHeenan/570535273be81eae35adaefe8c41e986

**Comment by pkienzle** [comment]
Okay, gist isn't convenient since it doesn't allow upload --- might as well paste code into the ticket.

The docs [claim](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests) you can upload a zip file, so let's put sphere_HSSQ.py into a zip file and try it: [sphere_HSSQ.zip](https://github.com/SasView/sasview/files/3064857/sphere_HSSQ.zip)

**Comment by RichardHeenan** [comment]
experiment - rename .py to .txt, drag into this box
[sphere_HSSQ - Copy.txt](https://github.com/SasView/sasview/files/3064929/sphere_HSSQ.-.Copy.txt)

**Comment by pkienzle** [comment]
Indeed, not coded.  I've provided support for returning mixture intermediates the same way as product intermediates.  In the process I addressed the TODOs in product.  I leave it to the Qt GUI programmers to take over the PR in sasview/sasmodels#216 and coordinate pulling with the state of ESS GUI.

**Comment by rozyczko** [comment]
Addressed now in ESS_GUI, after relevant changes in sasmodels got merged.

**Comment by rozyczko** [comment]
Moving to 5.1 so Richard can test it.
