### ISSUE TITLE
Dmax explorer : pressing enter closes window

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1463]
In the Dmax explorer pressing enter in any of the text entry fields activates the "Close" button rather than updating the values and plot. Enter key event should be bound to the update rather than close.

**Comment by smk78** [comment]
In my 5.0.1. release version on x64/W10 the Dmax explorer doesn't actually display any graphs either!

**Comment by rozyczko** [comment]
Fixed closing on Enter.

I'm perplexed with Steve's problem - does the graph show when you resize the DMax window? What about other charts in this window - what happens when you change the dependent variable?

**Comment by smk78** [comment]
Nope. Neither resizing or changing the dependent variable forces it to plot.

![image](https://user-images.githubusercontent.com/10938679/75179011-0f4dea80-5731-11ea-8855-35d6317d2f1a.png)

The Log Explorer reports
```
18:07:03 - INFO:  --- SasView session started ---
18:07:03 - INFO: Python: 3.6.7 (default, Dec  6 2019, 07:03:06) [MSC v.1900 64 bit (AMD64)]
18:07:48 - INFO: The estimated alpha for your system is too large. Try increasing your maximum distance.
18:07:48 - INFO: The estimated alpha for your system is too large. Try increasing your maximum distance.
18:07:48 - INFO: The estimated alpha for your system is too large. Try increasing your maximum distance.
18:07:59 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:08:02 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:08:05 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:08:07 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:08:47 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:09:47 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:10:07 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 81, in <lambda>
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
18:10:20 - ERROR: Traceback (most recent call last):
  File "site-packages\numpy\core\function_base.py", line 117, in linspace
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\sasview-5.0.1-py3.6-win-amd64.egg\sas\qtgui\Perspectives\Inversion\DMaxExplorerWidget.py", line 124, in modelChanged
  File "<__array_function__ internals>", line 6, in linspace
  File "site-packages\numpy\core\function_base.py", line 121, in linspace
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

**Comment by rozyczko** [comment]
This looks like a known numpy issue. Let's see how we can address this.
@smk78 Have you been using 5.0.2 release? 5.0.1 release? a local build?

**Comment by smk78** [comment]
So what I reported above was using the 5.0.1 release.

But I just pulled on ESS_GUI, built it locally, and ran it, and the Dmax explorer graphs are appearing! My Anaconda3 \pkgs folder has 4 numpy subfolders:

```
23/01/2020  14:50    <DIR>          numpy-1.16.4-py36hc71023c_0
23/01/2020  14:50         4,183,428 numpy-1.16.4-py36hc71023c_0.tar.bz2
23/01/2020  14:09    <DIR>          numpy-1.16.5-py37h19fb1c0_0
08/10/2019  17:08            51,160 numpy-1.16.5-py37h19fb1c0_0.tar.bz2
23/01/2020  14:15    <DIR>          numpy-base-1.16.5-py37hc3f5095_0
08/10/2019  17:02         4,313,201 numpy-base-1.16.5-py37hc3f5095_0.tar.bz2
23/01/2020  14:15    <DIR>          numpydoc-0.9.1-py_0
08/10/2019  17:06            31,957 numpydoc-0.9.1-py_0.tar.bz2
```
Does that help?

**Comment by rozyczko** [comment]
With Paul's fixes to the way linspace is called in the Dmax explorer, the issue should no longer be present.
@smk78 Can you please check this with the recent ESS_GUI installer? Also, can you please confirm the original bug (pressing enter closes window) is also fixed?

**Comment by smk78** [comment]
Tested ESS_GUI Build 357 on Win10/x64. Both bugs are fixed!
