### ISSUE TITLE
ESS_GUI: flakiness with OpenCL/no OpenCL selection

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1596]
Toggling opencl on and off in the os x gui can cause problems:
```
2020-06-16 11:24:27,560 : ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:3032) :: Traceback (most recent call last):
  File ".../sas/sascalc/data_util/calcthread.py", line 269, in _run
    self.compute(*args, **kwargs)
  File ".../sas/qtgui/Perspectives/Fitting/ModelThread.py", line 203, in compute
    return_data = self.model.calculate_Iq(self.data.x[index])
  File ".../sasmodels/sasview_model.py", line 715, in calculate_Iq
    return self._calculate_Iq(qx, qy)
  File ".../sasmodels/sasview_model.py", line 728, in _calculate_Iq
    calculator = self._model.make_kernel(q_vectors)
  File ".../sasmodels/kernelcl.py", line 442, in make_kernel
    return GpuKernel(self, q_vectors)
  File ".../sasmodels/kernelcl.py", line 575, in __init__
    self.q_input = GpuInput(q_vectors, dtype)
  File ".../sasmodels/kernelcl.py", line 525, in __init__
    env = environment()
  File ".../sasmodels/kernelcl.py", line 181, in environment
    raise RuntimeError("SAS_OPENCL=None in environment")
RuntimeError: SAS_OPENCL=None in environment
```

The environment is not being reset properly to select for dll, or perhaps the models are not being reloaded as dll models.

**Comment by toqduj** [comment]
Seems like previous kernels are not being reset when changing OpenCL environments. 
Further digging reveals that sasview_model.py reset_environment() method does not work, after setting a kernel, none of the model._model kernels contain any kernel.

**Comment by RichardHeenan** [comment]
On WIndows the models are nor recompiled until they need to be used, is it the same on Mac?

(see also issues with multiple graphics cards,  https://github.com/SasView/sasview/issues/1450)

**Comment by toqduj** [comment]
@RichardHeenan indeed, if you change the OpenCL settings before hitting the "compute" button, these issues don't appear.

**Comment by toqduj** [comment]
To replicate: 
Breakpoint e.g. at line 124 of sas/qtgui/Perspectives/Fitting (in set_sas_open_cl)
on mac os x start sasview, select cylinder/cylinder, press "compute" (and optionally follow with "show plot". 
Then change OpenCL method between CPU and GPU. 
step into sasmodels.sasview_model.reset_environment()
see that all model kernels are empty (no kernels to reset) by running on the debug console: [print(mod.model) for mod in MODELS.values() if mod._model is not None]

**Comment by toqduj** [comment]
Tests with Piotr showed that under Windows, the list comprehension above also shows an empty list. However, under Windows, the models are correctly regenerated after switching OpenGL options. 
The question is still out on where the difference in behaviour between the operating system is. Tests with Linux have not yet been done

**Comment by lucas-wilkins** [comment]
The descriptions of the code here seem quite unlike the current code. Pretty sure this is obsolete. Marking as stale, but really close to just closing this.

**Comment by butlerpd** [comment]
Given the discussion this afternoon between @wpotrzebowski and @lucas-wilkins is this actually more relevant than was being considered or is it in fact definitely obsolete?
