### ISSUE TITLE
Linux: SasView >5.0.1 binary cannot copy default custom_config.py

### ISSUE THREAD

**Issue by franzlang** [SasView/sasview#1640]
I have found that the Linux release binaries for SasView versions 5.0.1 and above give the following error when executing the run_sasview.sh script:
```
ERROR: Could not copy default custom config.
Traceback (most recent call last):
  File "sasview.py", line 117, in <module>
  File "site-packages/sasview-5.0.1-py3.6-linux-x86_64.egg/sas/qtgui/MainWindow/MainWindow.py", line 62, in run_sasview
  File "site-packages/sasview-5.0.1-py3.6-linux-x86_64.egg/sas/logger_config.py", line 43, in config_development
    self._disable_debug_from_config()
  File "site-packages/sasview-5.0.1-py3.6-linux-x86_64.egg/sas/logger_config.py", line 50, in _disable_debug_from_config
    custom_config = get_custom_config()
  File "site-packages/sasview-5.0.1-py3.6-linux-x86_64.egg/sas/__init__.py", line 44, in get_custom_config
  File "site-packages/sasview-5.0.1-py3.6-linux-x86_64.egg/sas/_config.py", line 98, in setup_custom_config
FileNotFoundError: [Errno 2] No such file or directory: '/home/my_home_folder_goes_here/.sasview/config/custom_config.py'

```
Version 5.0.0 works fine and creates the  custom_config.py file upon first launch. Once this file exists, versions 5.0.1 and above also launch.

**Comment by smk78** [comment]
As we are close to releasing 5.0.3, maybe this needs looking at?

**Comment by butlerpd** [comment]
given 5.0.3 has left the station am moving this to 5.0.4

**Comment by smk78** [comment]
Closing this issue in favour of #1672
