### ISSUE TITLE
Failure in getSymbolDict on selecting parameters for constraints

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1696]
In my current local build of this branch, the mutual constrain does not work, is there a commit of fix above needed still?  I get error
11:59:36 - ERROR: Traceback (most recent call last):
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 757, in showMultiConstraint
    self.addConstraintToRow(constraint=constraint, row=row)
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 810, in addConstraintToRow
    symbol_dict = self.parent.perspective().getSymbolDictForConstraints()
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\FittingPerspective.py", line 537, in getSymbolDictForConstraints
    symbol_dict.update(tab.getSymbolDict())
  File "C:\sasview42\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 4387, in getSymbolDict
    model_name = self.kernel_module.name
AttributeError: 'NoneType' object has no attribute 'name'

_Originally posted by @RichardHeenan in https://github.com/SasView/sasview/pull/1690#issuecomment-714415181_

**Comment by RichardHeenan** [comment]
Now that the previous branch has been merged to the new "main", my local build on win10 does not see this problem, so I am closing this ticket.
