### ISSUE TITLE
Mask Editor menu item does not grey out when no 2D data is loaded

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1778]
As reported by @wpotrzebowski in PR #1777.

The 2D mask editor is available when 2D data is loaded.  Accessing it used to be only from the fitpanel but in 5.x a menu item has been added: "Fitting --> Edit Mask"

When no file is selected in Data Manager the "Mask Editor" button on the fitpage (under the `Fit Options` tab) is greyed out an unavailable. However the menu item remains active.  clicking on it anyway leads to the following error: 
```
Traceback (most recent call last):
  File "site-packages/sasview-5.0.4-py3.6.egg/sas/qtgui/MainWindow/DataExplorer.py", line 1653, in extShowEditDataMask
  File "site-packages/sasview-5.0.4-py3.6.egg/sas/qtgui/MainWindow/DataExplorer.py", line 1681, in showEditDataMask
TypeError: must be str, not IndexError
``` 
The menu item should be disabled in tandem with the button on the fitpage

**Comment by rozyczko** [comment]
The behaviour of this menu item is slightly different. It looks at the **selected** items in the file explorer and applies mask if they are 2D. If no items are selected or items are 1D, the desired action is to show an error message.

This works for 1D selections but for no selections a wrong conditional is used. This can be easily fixed but we might want to rethink the behaviour of this action.

Enabling a menu item on selection is going to be expensive, since it will involve traversing a potentially large number of items in DataExplorer, checking the dimensions of each data object attached to the item.

Alternatively we can only enable this menu item if _any_  dataset is selected, delegating the dimension check to the current point - opening of the Mask dialog.
