### ISSUE TITLE
v5 errors when using S(Q) with a multiplicity model such as onion

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1816]
after adding an S(Q) to say onion, when I change the number of shells I get:

- ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2625, in onMainParamsChange
    self.kernel_module.setParam(parameter_name, value)
  File "C:\sasview5\sasmodels\sasmodels\sasview_model.py", line 513, in setParam
    raise ValueError("Model does not contain parameter %s" % name)
ValueError: Model does not contain parameter n_shells

I suspect that once S(Q) is included the F(Q) is then also not being computed correctly, as the effective radius in S(Q) is wrong, only including the first shell, so suspect n_shells is being passed as zero.

[also can someone please add a new milestone, for 5.0.5 ? ]

**Comment by pkienzle** [comment]
Maybe something in the GUI code which is not treating n_shells as a "multiplicity" parameter. The underlying `onion@hardsphere` model does define `n_shells` as a control parameter which the sasview_model wrapper should be turning into a multiplicity parameter. I think that means that the multiplicity parameter `n_shells` should not be modified in the model, but instead a new model created with the correct number of shells.

**Comment by butlerpd** [comment]
I think this is part of a larger issue of how the GUI handles control parameters from sasmodels. See for example https://github.com/SasView/sasmodels/issues/396 and #1897. Unfortunately this larger issues does not seem to have been noted in time to fix for this release.

**Comment by krzywon** [comment]
As noted in https://github.com/SasView/sasview/pull/2647, this was fixed in v5.0.6. Closing.
