### ISSUE TITLE
Check that using current 'master' bumps version does not break sasview

### ISSUE THREAD

**Issue by bmaranville** [SasView/sasview#1948]
A new release of bumps is planned soon (less than 2 weeks).  The requirements for sasview seem to set a lower bound on the bumps version, but not an upper bound.

There are some notes on the bumps README.rst about what is changing.

**Comment by krzywon** [comment]
I just pulled and installed bumps master and ran SasView main with it as part of my environment. I haven't looked at the bumps changes yet, but we should remain on [bumps v0.8.0](https://github.com/bumps/bumps/releases/tag/v0.8.0) for now.

Workflow:
- Load `apoferritin.txt`
- Send to fitting
- Select `Sphere` -> `sphere` for the model
- Check `scale`, `background`, and `radius`
- Fit using `Levenberg-Marquardt`: **No errors**
- Switch to `Nelder-Mead` and Fit: **Error [1]**
- Switch to `Differential Evolution` and Fit: **Error [1]**
- Switch to `DREAM` (unable to fit): **Error [2]**
- Switch to `Quasi-Newton` and Fit: **No errors**
- Switch to 'MPFit': **Error [3]**

[1] Results window is blank and the following error is thrown
> ERROR: Traceback (most recent call last):
  File "...\sasview\src\sas\qtgui\MainWindow\GuiManager.py", line 1007, in showFitResults
    self.results_panel.onPlotResults(output_data, optimizer=self.perspective().optimizer)
  File "...\sasview\src\sas\qtgui\Utilities\ResultPanel.py", line 72, in onPlotResults
    self.convergenceView.update(best, pop)
  File "...\qt5_win\lib\site-packages\bumps-0.8.0-py3.6.egg\bumps\gui\convergence_view.py", line 63, in update
    self.plot()
  File "...\qt5_win\lib\site-packages\bumps-0.8.0-py3.6.egg\bumps\gui\convergence_view.py", line 60, in plot
    pylab.draw()
  File "...\sasview\src\sas\qtgui\Utilities\PlotView.py", line 68, in __exit__
    Gcf._activeQue = [f for f in Gcf._activeQue if f is not self.fm]
AttributeError: type object 'Gcf' has no attribute '_activeQue'

[2] Unable to fit with DREAM engine and the following error is thrown when the algorithm is selected
> ERROR: Traceback (most recent call last):
  File "...\sasview\src\sas\qtgui\Perspectives\Fitting\FittingOptions.py", line 149, in onAlgorithmChange
    self.updateWidgetFromBumps(self.current_fitter_id)
  File "...\sasview\src\sas\qtgui\Perspectives\Fitting\FittingOptions.py", line 260, in updateWidgetFromBumps
    eval(widget_name).setText(str(options[option]))
  File "<string>", line 1, in <module>
AttributeError: 'FittingOptions' object has no attribute 'alpha_dream'

[3] A popup window opens with the following message and the previous algorithm remains selected in the `Fit Algorithms` window. I think this might be the expected behavior, but would be good to implement if we use the next version of bumps.
> This algorithm has not yet been implemented in SasView. Please choose a different algorithm.

**Comment by bmaranville** [comment]
Error [1] is probably not related to the bumps code changes... it seems to be arising in the sasview code.

**Comment by bmaranville** [comment]
The PlotView code in bumps was updated 15 months ago to account for _activeQue being dropped in newer matplotlib.  It would probably make sense to update the PlotPanel.__exit__() method in https://github.com/SasView/sasview/blob/main/src/sas/qtgui/Utilities/PlotView.py#L65 to match the update at https://github.com/bumps/bumps/blob/master/bumps/gui/util.py#L71

**Comment by bmaranville** [comment]
After commit e655e0c2d1f4ef1c846f82d7d954c484cad64ffa the DREAM error [2] doesn't seem to occur anymore (I did see it when I was on the ESS_GUI branch).  In that commit an explicit check is done to make sure bumps options loaded correspond to items defined in the UI, at https://github.com/SasView/sasview/blame/main/src/sas/qtgui/Perspectives/Fitting/FittingOptions.py#L254

So I think for the 'main' branch, if you fix PlotView, everything will work fine with the 'next' version of bumps.
