### ISSUE TITLE
Type error when closing plot window after fitting

### ISSUE THREAD

**Issue by Caddy-Jones** [SasView/sasview#1953]
Hi Guys
On the current SasView version on the main branch, there’s an error that occurs then closing the fitting graph window. The error is as follows

```
16:03:06 - ERROR: Traceback (most recent call last):
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\PlotterBase.py", line 321, in closeEvent
    self.clearQRangeSliders()
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\PlotterBase.py", line 334, in clearQRangeSliders
    slider.clear()
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\QRangeSlider.py", line 51, in clear
    self.clear_markers()
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\QRangeSlider.py", line 104, in clear_markers
    self.line_min.clear()
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\QRangeSlider.py", line 200, in clear
    self.clear_markers()
  File "C:\Local_repo\sasview\src\sas\qtgui\Plotting\QRangeSlider.py", line 313, in clear_markers
    self.input.textChanged.disconnect(self.inputChanged)
TypeError: 'method' object is not connected
```

**Comment by rozyczko** [comment]
this is known and addressed in this pull request:

https://github.com/SasView/sasview/pull/1943

**Comment by Caddy-Jones** [comment]
Ok cool, I must've missed that, I'll close this issue then
