### ISSUE TITLE
New Dependency Code broken again

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1987]
Downloading the Dec Release_5.0.5 Github build, Plotting still seems to be an issue.  Attempting to verify which version of matplotlib was being used I tried running both of the new functions: `Log installed packages` and `Log imported packages`.  Both failed and produced the following errors:
```python
18:03:47 - ERROR: Traceback (most recent call last):
  File "sas\qtgui\MainWindow\GuiManager.py", line 1181, in actionLog_installed_packages
  File "sas\qtgui\MainWindow\GuiManager.py", line 486, in log_installed_packages
AttributeError: 'PackageGatherer' object has no attribute 'log_installed_packages'
18:04:22 - ERROR: Traceback (most recent call last):
  File "sas\qtgui\MainWindow\GuiManager.py", line 1187, in actionLog_imported_packages
  File "sas\qtgui\MainWindow\GuiManager.py", line 492, in log_imported_packages
  File "sas\qtgui\MainWindow\PackageGatherer.py", line 51, in log_imported_packages
  File "sas\qtgui\MainWindow\PackageGatherer.py", line 114, in get_imported_packages
RuntimeError: dictionary changed size during iteration
``` 
Not sure if this is a problem in the Jenkins builds as well (I suspect not?) but if we are to release from github this will need to be addressed.

**Comment by rozyczko** [comment]
When the jenkins build is used, the plotting issues disappear - this is  some issue with mpl 3.x likely.
However, the dependency checker is failing with the same error(s) as posted by Paul.
This will have to be fixed.

**Comment by wpotrzebowski** [comment]
I beleive that reported error has been fixed https://github.com/SasView/sasview/commit/ec1e04ba1d46902f0d19e8248638e7adad0f4186 as it seems to work locally, however running from installer returns:
`08:31:12 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/MainWindow/GuiManager.py", line 1181, in actionLog_installed_packages
  File "sas/qtgui/MainWindow/GuiManager.py", line 486, in log_installed_packages
  File "sas/qtgui/MainWindow/PackageGatherer.py", line 34, in log_installed_modules
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 493, in run
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'pip'`
suggesting that we may need to ship pip with installer

**Comment by butlerpd** [comment]
Ah yes!!! that makes sense. I remember some discussion (that I only vaguely understood) about how to achieve the ends and pip was suggested. So I believe he is using pip in his code in order to pull out all the information in which case I guess the installer needs to have that since it has to be totally self contained?

**Comment by rozyczko** [comment]
We could include a precompiled `pip` binary, like the one in the Anaconda distribution.

**Comment by wpotrzebowski** [comment]
After some consideration the issues has been moved to 5.1. The backend code will stay as it is and front end menu items will be removed/commented out.

**Comment by wpotrzebowski** [comment]
git diff for removing functionality from GUI: 
`diff --git a/src/sas/qtgui/MainWindow/PackageGatherer.py b/src/sas/qtgui/MainWindow/PackageGatherer.py
index e1b20c2f4..d6a447706 100644
--- a/src/sas/qtgui/MainWindow/PackageGatherer.py
+++ b/src/sas/qtgui/MainWindow/PackageGatherer.py
@@ -6,7 +6,6 @@ import pathlib
 import sas
 
 logger = logging.getLogger(__name__)
-sys_modules = sys.modules.keys()
 
 class PackageGatherer:
     """ A class used to gather packages/modules  used by SasView and their current installed version
@@ -108,7 +107,7 @@ class PackageGatherer:
         standard_lib.extend(sys.builtin_module_names)
         standard_lib.append("sas")
 
-        for module_name in sys_modules:
+        for module_name in sys.modules.keys():
 
             package_name = module_name.split('.')[0]
 
diff --git a/src/sas/qtgui/MainWindow/UI/MainWindowUI.ui b/src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
index a502657d2..ef68a7b0f 100755
--- a/src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
+++ b/src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
@@ -155,9 +155,6 @@
     <addaction name="actionWelcomeWidget"/>
     <addaction name="separator"/>
     <addaction name="actionCheck_for_update"/>
-    <addaction name="separator"/>
-    <addaction name="actionLog_installed_packages"/>
-    <addaction name="actionLog_imported_packages"/>
    </widget>
    <addaction name="menu_File"/>
    <addaction name="menuEdit"/>
@@ -517,16 +514,6 @@
     <string>Check for update</string>
    </property>
   </action>
-  <action name="actionLog_installed_packages">
-   <property name="text">
-    <string>Log installed packages</string>
-   </property>
-  </action>
-  <action name="actionLog_imported_packages">
-   <property name="text">
-    <string>Log imported packages</string>
-   </property>
-  </action>
   <action name="actionExcel">
    <property name="text">
     <string>Excel</string>
`
