### ISSUE TITLE
5.x: Cannot load a plugin to a Fit Page if model_info.name differs from the filename

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1997]
5.0.4 and 5.0.5rc1 on W10/x64

I have a note in my crib sheet for my talk at the SHUG Workshop (so Aug 2021) that this bug present in the 5.0.4 release _was_ fixed in a development version of SasView I tried around that time. However, that fix has _not_ made it into 5.0.5rc1 and I can't find the earlier issue (if there was one!).

Basically, if the model_info.name in a plugin differs from the name of the plugin file, SasView will not load the plugin into the Fit Page.

This error is thrown:
```
16:39:47 - INFO: C:/Users/<user>/.sasview/plugin_models/stephen.py successfully saved.
16:40:03 - ERROR: Traceback (most recent call last):
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1277, in onSelectModel
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1418, in respondToModelStructure
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2411, in SASModelToQModel
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2460, in fromModelToQModel
  File "ntpath.py", line 216, in basename
  File "ntpath.py", line 185, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

In this example, stephen.py is:
```
from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('power_law+sphere+ellipsoid')
model_info.name = 'stephen2'
model_info.description = 'power+sphere+ellipsoid'
Model = make_model_from_info(model_info)
```

**Comment by butlerpd** [comment]
I strongly suspect this is linked to the issue about the name attribute being different from the filename #1443

**Comment by krzywon** [comment]
As noted by @butlerpd, this might be a duplicate of #1443.

**Comment by butlerpd** [comment]
Assuming `model_info.name` is in fact the `model.name` attribute in the `plugin.py` module then these are in  fact the same. @pkienzle would presumably know. If yes I suggest we close this but add the detail about the name in the plugin file being `model_info.name` parameter used in many places?
