### ISSUE TITLE
Freeze theory type error

### ISSUE THREAD

**Issue by murphyryanp** [SasView/sasview#2042]
I recently went to use the freeze theory function (using 5.0.4), both right clicking and using the button in theory. Both methods give the following type error about "can't pickle QLineEdit objects":

Right click method:
14:02:28 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Plotting\Plotter.py", line 569, in onFreeze
  File "copy.py", line 180, in deepcopy
  File "copy.py", line 280, in _reconstruct
  File "copy.py", line 150, in deepcopy
  File "copy.py", line 240, in _deepcopy_dict
  File "copy.py", line 169, in deepcopy
TypeError: can't pickle QLineEdit objects

Freeze theory button method:
14:03:27 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\MainWindow\DataExplorer.py", line 905, in freezeTheory
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\MainWindow\DataExplorer.py", line 932, in cloneTheory
  File "copy.py", line 180, in deepcopy
  File "copy.py", line 280, in _reconstruct
  File "copy.py", line 150, in deepcopy
  File "copy.py", line 240, in _deepcopy_dict
  File "copy.py", line 169, in deepcopy
TypeError: can't pickle QLineEdit objects

Screenshot in case this is not clear how it was generated:
![FreezeTheoryError](https://user-images.githubusercontent.com/30883207/167694435-b82036b7-767f-4377-9bb3-e13fc32f5408.png)

I didn't see this listed as a different issue with a quick search on "Freeze", so thought I would report it as a new issue. Apologies if this is already a known issue.

**Comment by krzywon** [comment]
Thanks for the report, @murphyryanp. The issue was originally reported in #1851 and has been fixed for the next release of SasView. If you would like to verify freeze theory works again, please download and try the latest [v5.0.5 release branch build](https://github.com/SasView/sasview/releases/tag/untagged-fde00ea7ff221c417778).

**Comment by smk78** [comment]
Does this mean https://github.com/SasView/sasview/issues/1418 can also be closed?

**Comment by murphyryanp** [comment]
Thanks, @krzywon ! 

Just tested the v5.0.5 build that you linked, and both freeze methods work. Sorry I didn't notice the original reported issue.

**Comment by butlerpd** [comment]
@smk78 - I believe the answer to #1418 closure is yes.  Note that while it mentioned the failure of the "Freeze theory" in 5.0.4 it was mostly about a difference in behavior between 4.x and 5.x. I think the consensus is that the new behavior is appropriate. Given that, and the fact that I don't believe there will be any more work on 4.x (and if there is one last push as was originally promised, changing that behavior would not seem like something to worry about) and since the Freeze Theory issue is fixed I would vote we close the ticket.
