### ISSUE TITLE
sasview fails to launch on Rocky Linux 8.6 - No module named 'sasdata'

### ISSUE THREAD

**Issue by dsclassen** [SasView/sasview#2183]
**Describe the bug**

sasview fails to launch

**To Reproduce**

download
setup new conda env
pip install -r build_tools/requirements.txt

**Expected behavior**

sasview should launch

**Screenshots**

```
(ssp-2.1) [08:23]user@fast_machine:~[1007]$ sasview
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/ssp-2.1/bin/sasview", line 33, in <module>
    sys.exit(load_entry_point('sasview==5.0.5', 'console_scripts', 'sasview')())
  File "/usr/local/miniconda3/envs/ssp-2.1/lib/python3.7/site-packages/sasview-5.0.5-py3.7.egg/sas/qtgui/MainWindow/MainWindow.py", line 113, in run_sasview
    mainwindow = MainSasViewWindow(screen_resolution)
  File "/usr/local/miniconda3/envs/ssp-2.1/lib/python3.7/site-packages/sasview-5.0.5-py3.7.egg/sas/qtgui/MainWindow/MainWindow.py", line 44, in __init__
    from .GuiManager import GuiManager
  File "/usr/local/miniconda3/envs/ssp-2.1/lib/python3.7/site-packages/sasview-5.0.5-py3.7.egg/sas/qtgui/MainWindow/GuiManager.py", line 27, in <module>
    import sas.qtgui.Utilities.GuiUtils as GuiUtils
  File "/usr/local/miniconda3/envs/ssp-2.1/lib/python3.7/site-packages/sasview-5.0.5-py3.7.egg/sas/qtgui/Utilities/GuiUtils.py", line 30, in <module>
    from sas.qtgui.Plotting.PlotterData import Data1D
  File "/usr/local/miniconda3/envs/ssp-2.1/lib/python3.7/site-packages/sasview-5.0.5-py3.7.egg/sas/qtgui/Plotting/PlotterData.py", line 7, in <module>
    from sasdata.data_util.uncertainty import Uncertainty
ModuleNotFoundError: No module named 'sasdata'
```

**SasView version (please complete the following information):**

HEAD of main branch 48a02ecb68b027e55c42061e52272c411be8c20b

**Operating system (please complete the following information):**

Rocky Linux 8.6

**Comment by krzywon** [comment]
Thanks for the report, @dsclassen. I just updated the [conda developer instructions](https://github.com/SasView/sasview/wiki/DevNotes_CondaDevEnviroment) to include how to get the sasdata package. Could you try the new instructions and report back?

**Comment by dsclassen** [comment]
Works for me. Thanks!
