### ISSUE TITLE
Batch fitting SESANS data fails

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2254]
User WouterG has reported a problem with batch fitting SESANS data. I have been able to reproduce it (on W10/x64).

Fitting the SESANS data individually still works. And batch-fitting SANS data works ok so this bug seems specific to SESANS.

The following traceback (or similar) is returned:
```
14:30:39 - INFO: 2022-10-17 14:30:39 === Steps: 5 of 200  chisq: 1.28  ETA: 3s
      M2.radius: 2.17e+04   |        M2.scale: 0.173      |
14:30:39 - INFO: 2022-10-17 14:30:39 === Steps: 5 of 200  chisq: 1.28  ETA: 3s
      M2.radius: 2.17e+04   |        M2.scale: 0.173      |
14:30:39 - ERROR: Fitting failed: Traceback (most recent call last):
  File "/opt/sasview5/lib/python3.9/site-packages/sas/qtgui/Perspectives/Fitting/FitThread.py", line 79, in compute
    result = list(map(map_apply, inputs))
  File "/opt/sasview5/lib/python3.9/site-packages/sas/qtgui/Perspectives/Fitting/FitThread.py", line 19, in map_apply
    return arguments[0](*arguments[1:])
  File "/opt/sasview5/lib/python3.9/site-packages/sas/qtgui/Perspectives/Fitting/FitThread.py", line 16, in map_getattr
    return  getattr(classInstance, classFunc)(*args)
  File "/opt/sasview5/lib/python3.9/site-packages/sas/sascalc/fit/BumpsFitting.py", line 291, in fit
    assert values is not None and errs is not None
AssertionError
14:30:39 - ERROR:  
 === Steps: 5 of 200  chisq: 1.28  ETA: 3s
      M2.radius: 2.17e+04   |        M2.scale: 0.173      |
14:30:39 - ERROR: Traceback (most recent call last):
  File "/opt/sasview5/lib/python3.9/site-packages/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 1764, in batchFitComplete
    results.append(page_name)
AttributeError: 'str' object has no attribute 'append'
```
It appears to go wrong when it tries to generate the table of batch results.

**To Reproduce**
Try batch-fitting the attached data. Use a sphere model.
[wouter.zip](https://github.com/SasView/sasview/files/9812003/wouter.zip)

**Expected behavior**
It should be possible to batch fit he SESANS data just like SANS data. 

**SasView version (please complete the following information):**
Releases 5.0.5 & 5.0.4 at least.

**Operating system (please complete the following information):**
W10

**Comment by llimeht** [comment]
Looking at that backtrace, it's the sort of thing that could be easily exposed via a test of the GUI as a first step to fixing it. There are basically no mentions of "sesans" anywhere in the GUI test suite at the moment, which is a bit of a hole.

Of course, #2252 needs to merge before making GUI tests can work.

If we can build functional GUI testing (as alluded to in #2239) the the entire end-to-end workflow can be tested routinely.

**Comment by smk78** [comment]
>There are basically no mentions of "sesans" anywhere in the GUI test suite at the moment, which is a bit of a hole.

To put it mildly...

**Comment by smk78** [comment]
Further (excellent) digging by the User, and verified by me, shows that the issue described arises when the data sets being batch fit have different numbers of datapoints!
