### ISSUE TITLE
Edit constraints from the Model tab does not work properly

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#2355]
**Describe the bug**
When a constraint has been defined (in the Constrained or Simultaneous Fit tab), it appears as blue in the Model or Polydispersity tab to indicate that it is no more a free parameter. By right-clicking in its corresponding Value box, a context menu is available allowing to select/deselect, remove or edit the constraint.

The select/deselect options work as expected, but not the other two. In addition, the behaviour is not the same for main and polydisperse (PD) parameters.

The remove constraint button effectively removes the constraint, but it removes also ALL the other constraints defined in the Model tab. BUT the remove button works as expected (deleting only the selected constraint) when it is applied to a PD parameter, or to scale or background. It is only when removing a model parameter, that all the other model parameters, including scale and background (but not the PD params) are removed.

The edit constraint button fails to launch the box when a main model parameter is selected, giving an error in the Log Explorer:
17:09:02 - ERROR: Traceback (most recent call last):
  File "C:\Users\gonzalezm\Git\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1050, in editConstraint
    if not np.any([FittingUtilities.isParamPolydisperse(p, self.model_parameters, is2D=self.is2D) for p in params_list]):
  File "C:\Users\gonzalezm\Git\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1050, in <listcomp>
    if not np.any([FittingUtilities.isParamPolydisperse(p, self.model_parameters, is2D=self.is2D) for p in params_list]):
  File "C:\Users\gonzalezm\Git\sasview\src\sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 963, in isParamPolydisperse
    if '.width' in param_name:
TypeError: argument of type 'NoneType' is not iterable

When applied to scale, background or a PD parameter, the box to define the constraint is correctly launched, but then it does not accept any new definition (the box background becomes red and only the cancel possibility is available)

**Expected behavior**
Remove should remove only the constraint of the selected parameter.
Define should update the constraint definition.

**Screenshots**
![image](https://user-images.githubusercontent.com/10974838/199057550-608267b4-52ed-451c-8c98-72b6e635d778.png)

**SasView version (please complete the following information):**
SasView 5.0.5 (ESS_GUI_constrain_poly branch to test the PD params)

**Operating system (please complete the following information):**
 Windows 10

**Comment by gonzalezma** [comment]
Fixed by PR #2743
