### ISSUE TITLE
linux manjaro install fails

### ISSUE THREAD

**Issue by toqduj** [SasView/sasview#2418]
perhaps related to #2416 , but when installing it on a fresh manjaro with the latest anaconda, I get the following issue:

(sasview) [brian@slab Downloads]$ sasview
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
15:01:36 - INFO: Custom config path: <module 'custom_config' from '/home/brian/.sasview/config/custom_config.py'>
Traceback (most recent call last):
  File "/home/brian/anaconda3/envs/sasview/bin/sasview", line 11, in <module>
    sys.exit(run_sasview())
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/qtgui/MainWindow/MainWindow.py", line 112, in run_sasview
    mainwindow = MainSasViewWindow(screen_resolution)
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/qtgui/MainWindow/MainWindow.py", line 44, in __init__
    from .GuiManager import GuiManager
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/qtgui/MainWindow/GuiManager.py", line 54, in <module>
    import sas.qtgui.Perspectives as Perspectives
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/qtgui/Perspectives/__init__.py", line 6, in <module>
    from .Inversion.InversionPerspective import InversionWindow
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/qtgui/Perspectives/Inversion/InversionPerspective.py", line 15, in <module>
    from sas.sascalc.pr.invertor import Invertor
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/sascalc/pr/invertor.py", line 29, in <module>
    from .p_invertor import Pinvertor
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/sascalc/pr/p_invertor.py", line 16, in <module>
    class Pinvertor(object):
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/sas/sascalc/pr/p_invertor.py", line 18, in Pinvertor
    x = np.empty(0, dtype=np.float)
  File "/home/brian/anaconda3/envs/sasview/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

**Comment by llimeht** [comment]
Yes, that's the same thing I've patched as linked in #2416. (You could apply that patch to check that there are no further numpy 1.24 issues)

**Comment by pbeaucage** [comment]
@toqduj - is this sourcing sasview from the conda package?  If so, can you try to pin numpy earlier and see if the environment still solves OK?  `conda install numpy<1.24` ought to do it.

If so, the fastest patch for this is for me to add such a version pin to our conda package.  That should provide an immediate fix for 5.0.5 while we wait for patches to be applied in the next release.

**Comment by llimeht** [comment]
Let's not start pinning dependencies when trivial patches exist. Pinning dependencies needs to be the last resort for when it is impossible to work around compatibility problems otherwise we get very quickly entangled in incompatible pins.

**Comment by llimeht** [comment]
You are right on all the above points. I normally wander away from sasview (for a period of months) when it gets too frustrating, precisely so that I don't inject grumpiness into the conversations.
