### ISSUE TITLE
Polydispersity settings not updating correctly

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2438]
**Describe the bug**
Changing polydispersity parameters 

**To Reproduce**
Make a P*S model,
Switch between polydispersity settings and change values
Things do not update consistently
Not diagnosed fully yet, seems to be intermittent at this point

**Comment by smk78** [comment]
Testing a recent 6.0.0a1 Github actions build on W10/x64.

Indeed, something bad has happened with Polydispersity!

![image](https://github.com/SasView/sasview/assets/10938679/33fd237a-4f66-470a-8ea9-8440c4f27fa4)

The function drop down is now appearing under Filename. The Filename box should only activate when an Array distribution is selected so that you can input your user-defined distribution.

Polydispersity still seems to function - and that is the only reason I'm not going to label this as a blocker for 6.0.0 - but I consider it highly undesireable that you can select a distribution other than a Gaussian and the GUI still says Gaussian.

This needs a prompt fix.

**Comment by smk78** [comment]
Changing function the following are thrown:
```
ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 3526, in File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 3580, in onPolyComboIndexChange AttributeError: 'NoneType' object has no attribute 'blockSignals'
```
```
2024-03-27 15:20:22,929 : ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:177) :: Traceback (most recent call last):
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 3526, in <lambda>
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 3580, in onPolyComboIndexChange
AttributeError: 'NoneType' object has no attribute 'blockSignals'
```

**Comment by krzywon** [comment]
> The function drop down is now appearing under Filename. The Filename box should only activate when an Array distribution is selected so that you can input your user-defined distribution.
> 
> Polydispersity still seems to function - and that is the only reason I'm not going to label this as a blocker for 6.0.0 - but I consider it highly undesireable that you can select a distribution other than a Gaussian and

I can reliably recreate the issue seen by @smk78, not only in v6.0.0a, but also v5.0.6.

Steps to repeat:
1. Load a data set and send it to fitting.
2. Select a model, and PD, but do not select a structure factor.
3. Select at PD parameter for fitting (important part).
4. Run the fit.
5. Select a new model -or- select a structure factor. The new model must have the parameter that was fit for PD in the original model.
6. The PD function now appears in the filename column.

There appear to be two signals created when the model changes, one related to polydispersity, and another related to the model. The model thread resets a flag saying there is error in the polydispersity value, and then deletes the error column in the PD tab. The PD thread reads the param table and uses the number of values in the list to determine if error exists, shifting the filename box into the filename column. Why the other columns aren't shifted, I can't be sure yet.

Note - more debugging and a fix are still needed, but I think this has been around for a while.

**Comment by dehoni** [comment]
The behaviour is persiting also in https://github.com/SasView/sasview/pull/3505
