### ISSUE TITLE
Cannot save parameters to file on Mac OSX in 5.0.6rc1

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2442]
**Describe the bug**
When trying to save parameters to file I am getting the following error:

`13:56:17 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 214, in onParamSave
  File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 3902, in onCopyToClipboard
  File "sas/qtgui/Perspectives/Fitting/FittingUtilities.py", line 811, in formatParametersExcel
IndexError: list index out of range`

**To Reproduce**
1. Choose a model and set up some parameters
2. Go to Edit in main menu
3. Clic on "Save params to file"

**SasView version (please complete the following information):**
 - Version: 5.0.6rc]

**Operating system (please complete the following information):**
 - OS: Mac OSX (however it may also occur on other platforms)

**Comment by smk78** [comment]
This would appear to gave many similarities to https://github.com/SasView/sasview/issues/2369.

**Comment by rozyczko** [comment]
Doesn't happen for me when a standard model is chosen, with multiciplity models, the failure happens as pointed out by @smk78

**Comment by krzywon** [comment]
potential duplicate
