### ISSUE TITLE
Broken "Constrained or Simultaneous Fit" button

### ISSUE THREAD

**Issue by lozanodorian** [SasView/sasview#2525]
**Describe the bug**
When a dataset is loaded, it is impossible to open the constraints page ("Const & Simul Fit Page").

The error message is : 
```
11:09:56 - sas.qtgui.Perspectives.Fitting.FittingWidget - ERROR - Traceback (most recent call last):
  File "sasview/src/sas/qtgui/MainWindow/GuiManager.py", line 1072, in actionConstrained_Fit
    per.addConstraintTab()
  File "sasview/src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py", line 284, in addConstraintTab
    tab	= ConstraintWidget(parent=self)
  File "sasview/src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py", line 161, in __init__
    self.initializeFitList()
  File "sasview/src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py", line 1043, in initializeFitList
    self.updateSignalsFromTab(tab)
  File "sasview/src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py", line 241, in updateSignalsFromTab
    if tab_object.receivers(tab_object.newModelSignal) > 0:
TypeError: 'PySide6.QtCore.QObject.receivers' called with wrong argument types:
  PySide6.QtCore.QObject.receivers(SignalInstance)
Supported signatures:
  PySide6.QtCore.QObject.receivers(bytes)
```

**To Reproduce**
1. Load one dataset
2. Click on "Send data to Fitting"
3. Click on "Fitting > Constrained or Simultaneous Fit"

Note : the problem remains with several datasets sent to fitting, and when a model is chosen for each dataset. However, the window appears (empty) if the datasets are not sent to fitting.

**Expected behavior**
A page ("Const. _Simul. Fit" in 5.0.5 version) should appear in the Fit panel.

**SasView version (please complete the following information):**
 - Version: 5.0.5 (commit 8142559 on main)

**Operating system (please complete the following information):**
 - OS: Linux

**Comment by lozanodorian** [comment]
Yes, sorry !
