### ISSUE TITLE
Python console not working in pyside

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#2556]
```
21:09:30 - ERROR: Traceback (most recent call last):
  File "…/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "…/site-packages/qtconsole/jupyter_widget.py", line 322, in _handle_kernel_info_reply
    super()._started_channels()
  File "…/site-packages/qtconsole/frontend_widget.py", line 616, in _started_channels
    self.reset(clear=True)
  File "…/site-packages/qtconsole/frontend_widget.py", line 660, in reset
    self._append_plain_text(self.banner)
  File "…/site-packages/qtconsole/console_widget.py", line 1024, in _append_plain_text
    self._append_custom(self._insert_plain_text, text, before_prompt)
  File "…/site-packages/qtconsole/console_widget.py", line 1002, in _append_custom
    result = insert(cursor, input, *args, **kwargs)
  File "…/site-packages/qtconsole/console_widget.py", line 2195, in _insert_plain_text
    cursor2.movePosition(cursor2.EndOfLine)
AttributeError: 'PySide6.QtGui.QTextCursor' object has no attribute 'EndOfLine'
```

**Comment by pkienzle** [comment]
Upgrading qtconsole from 5.3.0 to 5.4.3 fixed the problem.

Since our requirements file does not peg the qtconsole version it will pull the latest, so this should not affect release.
