### ISSUE TITLE
Orientation Viewer doesn't work from nigthly build (on Mac)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2577]
**Describe the bug**
Discovered while testing Mac installer but it may also occur on other platforms
Gives an error when trying to run:
07:41:09 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/MainWindow/GuiManager.py", line 1029, in actionOrientation_Viewer
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 293, in show_orientation_viewer
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 159, in __init__
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 210, in on_angle_changed
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 173, in _set_image_data
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 261, in scatering_data
  File "sasmodels/direct_model.py", line 375, in __call__
    return self._calc_theory(pars, cutoff=self.cutoff)
  File "sasmodels/direct_model.py", line 340, in _calc_theory
    Iq_calc = call_kernel(self._kernel, pars, cutoff=cutoff)
  File "sasmodels/direct_model.py", line 59, in call_kernel
    mesh = get_mesh(calculator.info, pars, dim=calculator.dim, mono=mono)
  File "sasmodels/direct_model.py", line 125, in get_mesh
    raise TypeError(f"Unused parameters in call: {', '.join(values.keys())}")
TypeError: Unused parameters in call: a, b, c

**To Reproduce**
1. Download nightly build
2. Try to run "Orientation Viewer"

**SasView version (please complete the following information):**
 - Version: nightly build

**Operating system (please complete the following information):**
 - OS: Mac OSX

**Comment by pkienzle** [comment]
The orientation viewer is using incorrect parameter names for parallelepiped. The new sasmodels kernel call correctly reports this.

The fix should be trivial: change orientation viewer calculator to use length_a, length_b, and length_c. There is also a typo in `background` in the original `jitter.py` code.

**Comment by pkienzle** [comment]
After fixing and merging the corrections to the orientation viewer the sasmodels PR https://github.com/SasView/sasmodels/pull/575 can be merged.

**Comment by wpotrzebowski** [comment]
Orientation viewer doesn't work again
```

07:40:52 - INFO:  --- SasView session started, version 6.0.0a1, 2023 ---
07:40:52 - INFO: Python: 3.8.17 (default, Jun  7 2023, 12:31:35) 
[Clang 13.0.0 (clang-1300.0.29.30)]
07:40:57 - ERROR: Traceback (most recent call last):
  File "sas/qtgui/MainWindow/GuiManager.py", line 1032, in actionOrientation_Viewer
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 293, in show_orientation_viewer
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 159, in __init__
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 210, in on_angle_changed
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 173, in _set_image_data
  File "sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py", line 261, in scatering_data
  File "sasmodels/direct_model.py", line 377, in __call__
    return self._calc_theory(pars, cutoff=self.cutoff)
  File "sasmodels/direct_model.py", line 342, in _calc_theory
    Iq_calc = call_kernel(self._kernel, pars, cutoff=cutoff)
  File "sasmodels/direct_model.py", line 59, in call_kernel
    mesh = get_mesh(calculator.info, pars, dim=calculator.dim, mono=mono)
  File "sasmodels/direct_model.py", line 126, in get_mesh
    raise TypeError(f"Unused parameters in call: {', '.join(values.keys())}")
TypeError: Unused parameters in call: a, b, c
```
