### ISSUE TITLE
Setting Simple Constraints on a Fitting page fails

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2687]
**Describe the bug**
Trying to set a simple constraint on a single Fit page causes errors and the constraint widget doesn't show up.

**To Reproduce**
1. Load a dataset
2. Send the dataset to fitting
3. Choose a model, any model
4. Try to constrain any two parameters
5. Observe the following error:

```
3:10:09 - ERROR: Traceback (most recent call last):

File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 762, 
in File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 787, in showMultiConstraint File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 787,

in File "sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 968, in isParamPolydisperse TypeError: argument of type 'NoneType' is not iterable
```

**Expected behavior**
The Simple Constraint widget pops up.

**SasView version (please complete the following information):**
 - Version: 6.0.0_alpha

**Operating system (please complete the following information):**
 - OS: Win10

**Additional context**
Fails in both installed version and developer version.

**Comment by rozyczko** [comment]
The same fix as in #2711 therefore closing this
