### ISSUE TITLE
constraint on parameter raises error

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2695]
**Describe the bug**
Trying to set a constraint on a parameter in 6.0.0 alpha throws a Traceback error
```
Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1053, in editConstraint File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1053, in File "sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 968, in isParamPolydisperse TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
1. load a data set (I used apoferritin)
2. send to fitting
3. choose a model (I used core shell sphere)
4. Select a parameter (I chose thickness)
5. Right click on that parameter and choose `Constrain parameter to its current value` from the drop down
6. Right click on same parameter and now choose `Edit constraint` from the drop down
7. The error is thrown

**Expected behavior**
Instead of an error there should be a box to enter a constraint

**SasView version (please complete the following information):**
 - Version: 6.0.0 alpha build from Dec 19, 2023

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
suspect this may be another pyside issue?

**Comment by wpotrzebowski** [comment]
I've tested it on Mac and I don't seem to have access to "Edit Constrain" menu
![Screenshot 2024-01-17 at 21 59 27](https://github.com/SasView/sasview/assets/4189922/4e874cdd-9b67-454a-a0d5-41c205d3ca3a)
I've checked that it is avaialable in 5.0.6

**Comment by gonzalezma** [comment]
This has been fixed by PR #2711. The edit button is not available any more (when constraining to current value), as the workflow to define constraints between parameters should be through the Constrained or Simultaneous Fit page. Only once a constraint has been defined there, the edit button will be available in the FitPage. This was done to simplify the logic and avoid having two different ways of doing the same action.
