### ISSUE TITLE
Merging local-document-generation branch broke SV

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2727]
**Describe the bug**
PR #2576 merged `local-document-generation` into `develop`: https://github.com/SasView/sasview/commit/9e3698b16b02654b8e8a2865c2e3b4b2855f9d34

This causes issues when starting SV from the dev build

```
Traceback (most recent call last):
  File "c:\projects\sasview\run.py", line 94, in <module>
    sys.exit(sas.cli.main(logging="development"))
  File "C:\projects\sasview\src\sas\cli.py", line 161, in main
    run_sasview()
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 106, in run_sasview
    mainwindow = MainSasViewWindow()
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 42, in __init__
    from .GuiManager import GuiManager
  File "C:\projects\sasview\src\sas\qtgui\MainWindow\GuiManager.py", line 37, in <module>
    from sas.qtgui.Utilities.DocViewWidget import DocViewWindow
  File "C:\projects\sasview\src\sas\qtgui\Utilities\DocViewWidget.py", line 13, in <module>
    from sas.sascalc.doc_regen.makedocumentation import make_documentation, HELP_DIRECTORY_LOCATION, MAIN_PY_SRC, MAIN_DOC_SRC
  File "C:\projects\sasview\src\sas\sascalc\doc_regen\makedocumentation.py", line 65, in <module>
    def get_py(directory: Union[Path, os.path, str]) -> list[Union[Path, os.path, str]]:
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 277, in inner
    return func(*args, **kwds)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 354, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 466, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 466, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\piotrrozyczko\.conda\envs\sasview\lib\typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'ntpath' from 'C:\\Users\\piotrrozyczko\\.conda\\envs\\sasview\\lib\\ntpath.py'>.
```

@gonzalezma reports that manually creating a `build` folder in docs/sphinx-docs is required to be able to run SV now.

**SasView version (please complete the following information):**
 - Version: `release_6.0.0`

**Operating system (please complete the following information):**
 - OS: Win10

**Comment by rozyczko** [comment]
Digging a bit deeper it seems that @krzywon used python >=3.10 syntax in several places
- using module as type (os.path)
- using `match` statement

If we are planning on not supporting 3.9, then this is fine, otherwise, it will have to be modified
