### ISSUE TITLE
Batch fitting fails in some cases for reasons unknown

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2749]
**Describe the bug**
Batch fitting fails with the error:
```
21:47:04 - ERROR: Traceback (most recent call last): 
File "D:\SasViewCodeDev\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1887, in onFit fitters, _ = self.prepareFitters() 
File "D:\SasViewCodeDev\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2140, in prepareFitters fitter_single.set_data(data=weighted_data, id=fit_id, smearer=smearer, qmin=qmin, 
File "D:\SasViewCodeDev\sasview\src\sas\sascalc\fit\AbstractFitEngine.py", line 461, in set_data fitdata.set_fit_range(qmin=qmin, qmax=qmax) 
File "D:\SasViewCodeDev\sasview\src\sas\sascalc\fit\AbstractFitEngine.py", line 209, in set_fit_range self._qmax_unsmeared = self.x[self._last_unsmeared_bin] 
IndexError: index 121 is out of bounds for axis 0 with size 102
```

**To Reproduce**
1. Run SasView
2. From \\test or \\example_data, load ISIS_Polymer_Blend_RT2.xml & ISIS_Polymer_Blend_TK49.xml
3. Select just one of these and Send to Fitting, fit to _poly_gauss_coil_
4. Select both datasets, check Batch fit, and Send to Fitting
5. Go to the first FitPage, Copy params, go to the Batch fit page, paste params
6. On the Batch fit page, click fit
7. Observe the error
8. Restart SasView
9. Repeat the batch fitting with the AOT_Microemulsion datasets (fitting to a _sphere_)
10. Observe there is no error this time

**Expected behavior**
The Batch Fitting Results table should appear in both cases **or** a sensible error message should be displayed

**SasView version (please complete the following information):**
 - Version: multiple versions including dev builds

**Operating system (please complete the following information):**
 - OS: W10/x64, but probably affects all platforms

**Additional context**
The only obvious difference between the two ISIS_Polymer_Blend datasets is that they span _slightly_ different Q-ranges.

**Comment by gonzalezma** [comment]
This is happening because the first set has 123 points and the second one only 102. In FitData1D.set_fit_range(...), the attributes _qmin_unsmeared and _qmax_unsmeared are set from the Q values of the first and last bins, and it seems that these are determined only for the first set and applied them to all the others.
This means that if one fits first the RT2 set (123 points) the error will happen, while if one fits first the TK49 set, the batch fit succeeds. It also works if one uses Resolution None. Keep working on this ...
