### ISSUE TITLE
Draw throws an error in the Generic Scattering Calculator in 6.0.0a1

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2818]
**Describe the bug**
Using installers from PR based off of 6.0.0a1 (PR #2565 and #2785 so far) attempting to render the real space view of the loaded structure vile (vtk or pdb, magnetic or not) by clicking the `draw` button thows the following error
```python
Traceback (most recent call last): File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 126, in File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1544, in plot3d File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1797, in __init__ File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1597, in __init__ File "sas\qtgui\Plotting\PlotterBase.py", line 30, in __init__ RuntimeError: You can't initialize an PySide6.QtWidgets.QWidget object in class Plotter3D twice!
```
Note that 5.0.6 works as expected

**To Reproduce**
1. load the generic scattering calculator tool
2. Load a data file (nuclear or magnetic - I tried pdb, oomf and vtk)
3. Once the file has loaded click draw

**Expected behavior**
The behavior should be as in 5.0.6

**SasView version (please complete the following information):**
 - Version: release_6.0.0 branch

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by butlerpd** [comment]
issue was addressed by now merged PR #2824 so closing
