### ISSUE TITLE
2D Viewing Option Selection after selecting Custom Pinhole Smear throws an error

### ISSUE THREAD

**Issue by juliuskarliczek** [SasView/sasview#2840]
**Describe the bug**
When creating a new model after startup, and selecting the Custom Pinhole Smearing for the 1D View, checking the checkbox for 2D Viewing in the Fitpanel under Model/Options/2DView throws an error.

**To Reproduce**
1. Start SasView
2. Create new Model (in my case: Category: Cylinder, Model name: barbell
3. Go to Resolution Tab
4. Select Custom Pinhole Smear
5. Enter a value in dQ/Q, e.g. 1
6. Go back to Model tab
7. check 2DView checkbox

**Expected behavior**
The dQ/Q value from 1d version is entered into the 2d version, but still throws the error

**Screenshots**
![image](https://github.com/SasView/sasview/assets/165785299/83b38905-211b-4428-b8d8-850ce1bff5c7)
![image](https://github.com/SasView/sasview/assets/165785299/464c5d9d-4045-4c94-8504-cc8d83be629a)

**SasView version (please complete the following information):**
 branch release_6.0.0

**Operating system (please complete the following information):**
 - OS: Win10

**Comment by butlerpd** [comment]
Good catch. I get a similar error when (using 5.0.6) switching from 2D to 1D (by unchecking the 2D view checkbox).
```python
13:49:02 - INFO:  --- SasView session started, version 5.0.6, 2023 ---
13:49:02 - INFO: Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
13:50:48 - ERROR: Traceback (most recent call last):
  File "sas\sascalc\data_util\calcthread.py", line 269, in _run
  File "sas\qtgui\Perspectives\Fitting\ModelThread.py", line 184, in compute
AttributeError: 'PySmear2D' object has no attribute 'get_bin_range'
```
Note this time however it is not PySmear but PySmear2D that throws the error. This suggest that when checking or unchecking code is launched behind the scenes (why) that is using the previous smearing routine on the new data object (so PySmear on a data2D and PySmear2D on a data1D object?)
