### ISSUE TITLE
Mac installer from main branch is not starting

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2846]
**Describe the bug**
After starting Mac installer it crashes silently. Running it from the terminal gives an error

```
Traceback (most recent call last):
  File "sasview.py", line 15, in <module>
  File "sas/cli.py", line 135, in main
  File "sas/system/lib.py", line 17, in setup_sasmodels
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sas/sascalc/fit/models.py", line 18, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sasmodels/sasview_model.py", line 30, in <module>
    from . import weights
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sasmodels/weights.py", line 11, in <module>
    from scipy.special import gammaln  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "scipy/special/__init__.py", line 777, in <module>
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._cdflib'
[41201] Failed to execute script 'sasview' due to unhandled exception: No module named 'scipy.special._cdflib'
[41201] Traceback:
Traceback (most recent call last):
  File "sasview.py", line 15, in <module>
  File "sas/cli.py", line 135, in main
  File "sas/system/lib.py", line 17, in setup_sasmodels
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sas/sascalc/fit/models.py", line 18, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sasmodels/sasview_model.py", line 30, in <module>
    from . import weights
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sasmodels/weights.py", line 11, in <module>
    from scipy.special import gammaln  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "scipy/special/__init__.py", line 777, in <module>
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._cdflib' 
```
suggesting some issue with scipy

**To Reproduce**
1. Download SasView artifact for main 
2. Run it

**SasView version (please complete the following information):**
 - Version: main

**Operating system (please complete the following information):**
 - OS: macOS Sonoma 14.3

**Comment by juliuskarliczek** [comment]
I just downloaded the windows installer artifact for pr #2848 and tried to install and execute, when the same error appeared.
`Traceback (most recent call last):
  File "sasview.py", line 15, in <module>
  File "sas\cli.py", line 135, in main
  File "sas\system\lib.py", line 17, in setup_sasmodels
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "sas\sascalc\fit\models.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "sasmodels\sasview_model.py", line 30, in <module>
    from . import weights
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "sasmodels\weights.py", line 11, in <module>
    from scipy.special import gammaln  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "scipy\special\__init__.py", line 777, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._cdflib'
`

I dont know if this could be helpful in any way, but maybe still mentionable?
[https://github.com/Nuitka/Nuitka/issues/2807](url)

**Comment by andyfaff** [comment]
scipy 1.13.0 works from a REPL on macOS Sonoma 14.3:
```
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> from scipy.special import gammaln
>>> 
```
It'll be an issue in pyinstaller, perhaps the scipy hook needs patching.

**Comment by andyfaff** [comment]
It looks as if it's fixed in https://github.com/pyinstaller/pyinstaller/commit/5fe069177c9fda8ae7e362cdaa5b39c5b64fe4f5

**Comment by krzywon** [comment]
I believe this has been fixed. Closing unless someone says otherwise
