### ISSUE TITLE
Moving Sliders in Corfunc throws errors

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2912]
**Describe the bug**
Moving the sliders (the Porod ones at least) in Corfunc throws the following error, although the sliders do update!

```
15:45:10 - ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Corfunc\CorfuncPerspective.py", line 636, in on_extrapolation_slider_changing File "sas\qtgui\Perspectives\Corfunc\QSpaceCanvas.py", line 45, in update_lines File "matplotlib\lines.py", line 1289, in set_xdata RuntimeError: x must be a sequence
15:45:10 - ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Corfunc\CorfuncPerspective.py", line 636, in on_extrapolation_slider_changing File "sas\qtgui\Perspectives\Corfunc\QSpaceCanvas.py", line 45, in update_lines File "matplotlib\lines.py", line 1289, in set_xdata RuntimeError: x must be a sequence
15:45:10 - ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Corfunc\CorfuncPerspective.py", line 636, in on_extrapolation_slider_changing File "sas\qtgui\Perspectives\Corfunc\QSpaceCanvas.py", line 45, in update_lines File "matplotlib\lines.py", line 1289, in set_xdata RuntimeError: x must be a sequence
```

**Comment by lucas-wilkins** [comment]
@smk78 I can't reproduce this.

**Comment by smk78** [comment]
@lucas-wilkins , I can! W10/x64.

![image](https://github.com/SasView/sasview/assets/10938679/3c9435bc-6ab3-4378-b76d-da293e3eb32a)

![image](https://github.com/SasView/sasview/assets/10938679/76c99b24-83c6-46a1-b2cf-b3ff517e3389)

Grab righthand slider and drag.

![image](https://github.com/SasView/sasview/assets/10938679/33c317d1-ac94-4677-a7d6-a9bbc94828b4)

**Comment by lucas-wilkins** [comment]
Seems fine on my dev version, but the installed version is different, maybe a matplotlib version issue?
