### ISSUE TITLE
quick plots no longer possible after fitting a restricted Q range

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3056]
**Describe the bug**
This is apparently **not** easily reproducible. However given a traceback error was captured, I am reporting it as an issue. This error seems to occur much more frequently on Macs, but has occasionally been reported by Windows users as well.

This error is reported to happen after restricting the Q range of a fit (in the FitPage `Options` tab) from the full range available in the data file.  Plotting (quick plot, or send to plot) or saving the structure factors no longer work. The log explorer window gives the following error:

``` python
11:21:14 - ERROR: Traceback (most recent call last): File "sas\qtgui\MainWindow\DataExplorer.py", line 1678, in quickDataPlot
File "sas\qtgui\Plotting\Plotter.py", line 131, in plot 
File "sas\qtgui\Utilities\GuiUtils.py", line 864, in xyTransform
File "sas\qtgui\Plotting\Plottables.py", line 577, in transformView
File "sas\qtgui\Plotting\Plottables.py", line 693, in transform ValueError: Plottable.View: Given y and x are not of the same length
```

**SasView version (please complete the following information):**
 - Version: 6.0.0b2 and 5.0.6 and possibly before

**Operating system (please complete the following information):**
 - OS: Mac mostly but also seen on Windows

**Additional context**
Identified during the NIST CNR summer school. However, given it is hard to reproduce and that it is reported to have happened in previous version and that it does not cause incorrect results to be published I am not going to label it with the 6.0.0 release label.

**Comment by krzywon** [comment]
This has been around for a while and should not be included in release 6 unless it needs to be fixed to fix another 6.0 specific issue. I'm removing it from the hackathon project list.

**Comment by jamescrake-merani** [comment]
Was having a play around with this in advance of the code camp, and I'm not able to reproduce it on Linux (running with the Flatpak). Has this issue been reproduced since the 6.0.0 release? Unfortunately, I don't currently have a Mac with me so I can't test it on there.
