### ISSUE TITLE
Reinstate the documentation generation routines

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#3132]
**Describe the bug**
Due to some late issues related to the documentation generation processes, they were disabled for the final v6.0.0 release. This is to track and note this all should be reinstated, as early as v6.0.1.

**Comment by ehb54** [comment]
So is this why I don't have working help in the v6.0.0 linux release packages?
(Installed in a container ubuntu:20.04, also tried ubuntu:22.04, same results)

This is the response from `Help->Documentation`
![image](https://github.com/user-attachments/assets/e4a8297d-f5d6-4115-9ba0-15b5565fc484)

And below, clicking `Help` on the `Fit Panel`
![image](https://github.com/user-attachments/assets/863dd1ef-b915-49ea-b41d-f8f05f8ee5c4)

Here's what I get from flatpak on Rocky 8.10
`Help->Documentation`
![image](https://github.com/user-attachments/assets/36881362-8bb3-4f13-aa15-d2c41323564a)

`Help` on the `Fit Panel`
![image](https://github.com/user-attachments/assets/cea0c5f4-77de-40ab-9a6d-879246253340)

**Comment by ehb54** [comment]
Note - I also had a documentation issue on OSX at the SAS2024 tutorial. 
Windows seemed to work.

**Comment by jamescrake-merani** [comment]
> Note - I also had a documentation issue on OSX at the SAS2024 tutorial.

What specifically was the problem? I just tried it on the Mac we have in our team, and I could access the documentation from Help -> Documentation but I couldn't access the model documentation from clicking the Help button in the fitting window. I got the following error instead

```08:03:14 - ERROR: Traceback (most recent call last): File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 1891, in onHelp File "sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 1903, in getHelpLocation KeyError: 'Plugin Models'```

I was curious as to whether you got the same problem, something additional that doesn't work, or if its completely different on your machine?

**Comment by butlerpd** [comment]
In principle this should not cause the problem pointed out by @ehb54.  This should only have prevented plugin model docs from generating (which has always been the case - this was to add a new feature that compiled plugin model docs on the fly).  But it is possible that it is due to some of the folder location changes in 6.0. In which case, were this "doc regeneration" working, it would have dealt with that problem?  @krzywon would be most likely to know.

I'm curious @jamescrake-merani - the error you show is looking at `Plugin Models` which I think is where this leads to a problem? but I'm guessing you actually were clicking on help for a built in model? Is that correct?

**Comment by jamescrake-merani** [comment]
> but I'm guessing you actually were clicking on help for a built in model? Is that correct?

Yes I was looking at the sphere model which should be a builtin model to my understanding.

Looking at the error, this is the line in `FittingWidget.py` where it is happening

```python
plugin_names = [name for name, enabled in self.master_category_dict[CATEGORY_CUSTOM]]
```

This seems to be the function where that `self.master_category_dict` is actually set.

```python
    def readCategoryInfo(self):
        """
        Reads the categories in from file
        """
        self.master_category_dict = defaultdict(list)
        self.by_model_dict = defaultdict(list)
        self.model_enabled_dict = defaultdict(bool)

        categorization_file = CategoryInstaller.get_user_file()
        if not os.path.isfile(categorization_file):
            categorization_file = CategoryInstaller.get_default_file()
        with open(categorization_file, 'rb') as cat_file:
            self.master_category_dict = json.load(cat_file)
            self.regenerateModelDict()

        # Load the model dict
        models = load_standard_models()
        for model in models:
            self.models[model.name] = model

        self.readCustomCategoryInfo()
```
I don't have a debugger to play around with on the Mac but I wonder if it is something to do with this `categorization_file`. But yes its still also strange that its looking for plugin models.
