### ISSUE TITLE
Error when plotting models

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3159]
**Describe the bug**
This one seems to depend on some particular paths in the code but is reproducible. When activated, changing a parameter in the model and hitting "return" (NOT not just click away!!) the entire model parameter window goes blank
![NoParams](https://github.com/user-attachments/assets/36c5f0e2-bbba-4e3a-9ca6-624e22f3b45d)

**To Reproduce**
1. Start SasView
2. Add a model to the first fit page (e.g. sphere)
3. Turn on polydispersity
4. Set polydispersity (e.g. to .1)
5. calculate, then plot
6. Create a second fit page
7. add the exact same model (in this case "sphere")
8. Calculate, then plot
9. Return to first fit page
10. change the value of a parameter (I tried scale and radius so far) and **HIT RETURN** this step is important. Apparently just clicking away avoids the error path
11. the parameter screen goes blank
12. choose some other action (e.g. hit "Compute/Plot" or even just try to quit the program
13. Monster error pops up.
14. System is now in weird state. hitting "Compute/Plot" now throws the following error
```python
16:19:27 - ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2461, in onPlot File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2500, in showTheoryPlot RuntimeError: Internal C++ object (HashableStandardItem) already deleted.
```
15.  I recommend exiting the program at this point (click quit a second time if the error was generated on the first click)

**deduced so far**
* The two fitpages **must** use the same model
* Only the first fitpage needs to have polydispersity set.
* But -- the first model must be run with polydispersity set (not just turned on .. so some non zero value) PRIOR to starting the second fitpage

**SasView version (please complete the following information):**
 - Version: 6.0.0

**Operating system (please complete the following information):**
 - OS: tested on Windows 10

**Comment by jamescrake-merani** [comment]
I am able to reproduce this bug on both Linux, and Mac but I seem to get slightly different behaviour on both systems.

On Linux, the parameters don't go blank but I get this error everytime I try to compute/plot

```11:25:21 - ERROR: Traceback (most recent call last): File "/app/lib/python3.11/site-packages/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 2461, in onPlot self.showTheoryPlot() File "/app/lib/python3.11/site-packages/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 2500, in showTheoryPlot self._requestPlots(self.model_data.name, self.theory_item.model()) ^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: Internal C++ object (HashableStandardItem) already deleted.```

On the Mac, the behaviour is very similar to what you describe. All the parameters go blank, and the errors I get are considerably longer. I won't paste them here because it would take up the whole page but yes they are very monstrous, and its not exactly clear whats happening.

Given that the error above seems to be coming from C++, my guess is that something is going wrong with QT which would also explain why the behaviour is slightly different depending on the platform. The Linux error seems to be a lot more concise so that might give us a good starting point to debug the problem.

**Comment by jamescrake-merani** [comment]
It looks like the `HashableStandardItem` in `self.theory_item` of `FittingWidget.py` is the culprit. Somewhere, it has been deleted from memory but we are trying to access it when plotting it seems.

**Comment by jamescrake-merani** [comment]
I think I know what the problem is.

When I run my first model with polydispersity, this is what I see on the data explorer.

![image](https://github.com/user-attachments/assets/80fd94c9-0e28-49d4-b715-49cb33466310)

Note in particular the second 'M1 radius polydispersity' item. Now I start a new fit page with the same model, and click calculate. Everything works fine, but look at the data explorer now.

![image](https://github.com/user-attachments/assets/d20afea8-cad0-49bf-995a-4fe1ce54e4c6)

You'll notice the polydispersity item has now gone.

In the `DataExplorerWindow` class, it seems this is where the theory data sets are kept.

```python
# Secondary model for keeping frozen data sets
self.theory_model = QtGui.QStandardItemModel(self)
```

Recall the error message

```16:19:27 - ERROR: Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2461, in onPlot File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2500, in showTheoryPlot RuntimeError: Internal C++ object (HashableStandardItem) already deleted.```

What I think is happening is that, in `FittingWidget.py`, the `self.theory_item` is a reference to an item which used to exist in `theory_model` of `DataExplorerWindow` but which has been deleted from that model, and thus deleted from memory. Which explains the errors.

I need to work out why they are being deleted so I'm going to create a branch to play around in, and see if I can fix the problem.

**Comment by jamescrake-merani** [comment]
I've opened a pull request to fix this issue (#3160) but I need to discuss this at the call as it may break other functionality (see the PR for more details).

The issue was with the `deleteIntermediateTheoryPlotsByModelID` method in `DataExplorer.py`. This is called when the calculate button is clicked on the fitting page. Because it was going by model id, since both fit pages were using the same model, it wanted to delete the polydispersity data from the other tab since it was part of the same model.
