### ISSUE TITLE
Failure to assign model when using attached data file (Trac #269)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#417]
When sending the attached file to fitting, a blank fit panel occurs and assigning the model fails with:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py", line 1181, in _on_select_model
    self.onSmear(None)
  File "/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py", line 2587, in onSmear
    temp_smearer = self.on_smear_helper()
  File "/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py", line 2613, in on_smear_helper
    self._get_smear_info()
  File "/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py", line 1586, in _get_smear_info
    self.dq_l = data.dx[0]
IndexError: index out of bounds

It seems it is trying to assign dq_l when this dataset has no smearing information (pinhole SAXS from I22 at Diamond).

The cansas1D file was created by me using a python script which I believe produces standard compliant files. The data file and script are attached. 

Migrated from http://trac.sasview.org/ticket/269
```json
{
    "status": "closed",
    "changetime": "2015-02-18T11:29:46",
    "_ts": "2015-02-18 11:29:46.746119+00:00",
    "description": "When sending the attached file to fitting, a blank fit panel occurs and assigning the model fails with:\n\nTraceback (most recent call last):\n  File \"/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py\", line 1181, in _on_select_model\n    self.onSmear(None)\n  File \"/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py\", line 2587, in onSmear\n    temp_smearer = self.on_smear_helper()\n  File \"/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py\", line 2613, in on_smear_helper\n    self._get_smear_info()\n  File \"/usr/lib64/python2.6/site-packages/sasview-3.0.0_r7073-py2.6-linux-x86_64.egg/sans/perspectives/fitting/fitpage.py\", line 1586, in _get_smear_info\n    self.dq_l = data.dx[0]\nIndexError: index out of bounds\n\nIt seems it is trying to assign dq_l when this dataset has no smearing information (pinhole SAXS from I22 at Diamond).\n\nThe cansas1D file was created by me using a python script which I believe produces standard compliant files. The data file and script are attached. \n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-07-07T18:34:45",
    "component": "SasView",
    "summary": "Failure to assign model when using attached data file",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2014/07/07 18:35:35`: 
* **ajj** changed attachment from "" to "convert-to-ascii.py"
* **ajj** commented:

Script to convert 2013 DAWN output to cansas XML

**Comment by ajj** [comment]
Trac update at `2014/07/07 18:36:02`: 
* **ajj** changed attachment from "" to "113217.xml"
* **ajj** commented:

Datafile that causes problems

**Comment by ajj** [comment]
Trac update at `2014/07/07 18:37:20`: 
* **ajj** commented:

Assigning to Jeff as he knows the innards of the readers.


* **ajj** changed milestone from "SasView Next Release +1" to "SasView 3.0.1"
* **ajj** changed owner from "" to "krzywon"
* **ajj** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2014/07/07 18:57:40`: **ajj** commented:

So loading cansas assumes that there must be resolution data?

The cansas spec does not require any error or resolution information - minimum requirement is I and Q. 

We load other data with no resolution and no dI (2 column ascii) and that works fine - the same should be true for cansas xml. If setting the data1D arrays to zeros is how we handle that for 2 column data, then the same answer should be done for cansas.

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"
