### ISSUE TITLE
Errors generated in mac log on loading project (Trac #440)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#574]
On mac when loading project, the following is repeated multiple times:

```text
Traceback (most recent call last):
  File "/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16767, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/pkienzle/Source/sasview/src/sas/guiframe/data_panel.py", line 689, in load_data_list
    process.__str__())
  File "/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 5138, in AppendItem
    return self.DoInsertItem(parent, len(parent.GetChildren()), text, ct_type, wnd, image, selImage, data)
  File "/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py", line 4886, in DoInsertItem
    raise Exception("\nERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT")
Exception: 
ERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT
```

Check to see if easy to fix or if any serious user facing problem - else bump to next release

Migrated from http://trac.sasview.org/ticket/440
```json
{
    "status": "closed",
    "changetime": "2015-07-02T14:25:27",
    "_ts": "2015-07-02 14:25:27.659448+00:00",
    "description": "On mac when loading project, the following is repeated multiple times:\n{{{\nTraceback (most recent call last):\n  File \"/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py\", line 16767, in <lambda>\n    lambda event: event.callable(*event.args, **event.kw) )\n  File \"/Users/pkienzle/Source/sasview/src/sas/guiframe/data_panel.py\", line 689, in load_data_list\n    process.__str__())\n  File \"/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py\", line 5138, in AppendItem\n    return self.DoInsertItem(parent, len(parent.GetChildren()), text, ct_type, wnd, image, selImage, data)\n  File \"/Users/pkienzle/anaconda/envs/bumps/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/lib/agw/customtreectrl.py\", line 4886, in DoInsertItem\n    raise Exception(\"\\nERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT\")\nException: \nERROR: In Order To Append/Insert A MultiLine Text You Have To Use The Style TR_HAS_VARIABLE_ROW_HEIGHT\n}}}\n\nCheck to see if easy to fix or if any serious user facing problem - else bump to next release",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-06-30T17:15:30",
    "component": "SasView",
    "summary": "Errors generated in mac log on loading project",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/06/30 23:24:24`: **butler** commented:

Testing jenkins installer on mac I find only the same problem as on PC and that seems to be due to a problem in the invariant panel. The panel seems to work and saving and loading seems to work but just going to the invariant panel will generate the same errors as one sees on loading the project.  Thus does not seem to be a problem with project.  Depending on other testers this can be closed but probably need to open a ticket to look at invariant panel.

**Comment by mdoucet** [comment]
Trac update at `2015/07/02 14:25:27`: 
* **mathieu** commented:

These errors were generated by the "process" info in the data panel. The tree control doesn't accept multi-line text entries, which is what the string representation of the process info object is. I first made sure that the UI tries to add the process info only if it's not empty (which it nearly always is), then used a single-line representation. 



* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"
