### ISSUE TITLE
Selecting an S(Q) causes SasView 4.0-alpha to hang (Trac #547)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#679]
Pulled and built SasView locally at ~12:00 GMT. Loaded data - it displayed. Chose a model - fit page opened and data/model/residuals displayed. Selected an S(Q) model and the whole application hung (not crashed).

Migrated from http://trac.sasview.org/ticket/547
```json
{
    "status": "closed",
    "changetime": "2016-03-21T17:43:25",
    "_ts": "2016-03-21 17:43:25.345697+00:00",
    "description": "Pulled and built SasView locally at ~12:00 GMT. Loaded data - it displayed. Chose a model - fit page opened and data/model/residuals displayed. Selected an S(Q) model and the whole application hung (not crashed).",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-03-21T13:41:48",
    "component": "SasView",
    "summary": "Selecting an S(Q) causes SasView 4.0-alpha to hang",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/03/21 13:44:58`: **smk78** commented:

Update:
At the point you click on an S(Q) model, Eclipse reports:

Traceback (most recent call last):
  File "C:\Code\sasview-local-trunk\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1181, in _on_select_model
    self._on_select_model_helper()
  File "C:\Code\sasview-local-trunk\src\sas\sasgui\perspectives\fitting\basepage.py", line 2148, in _on_select_model_helper
    from sas.models.!MultiplicationModel import !MultiplicationModel
!ImportError: No module named models.!MultiplicationModel
