### ISSUE TITLE
Old-style custom models don't load (Trac #744)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#860]
Old style python custom model don't load. It was fixed before but apparently the issue reoccurred. It doesn't work either on windows or mac (regardless opencl or not).

Traceback (most recent call last):
  File "C:\Users\wojtek\SASVIEW_WORKSPACE\sasview\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1179, in _on_select_model
    self._on_select_model_helper()
  File "C:\Users\wojtek\SASVIEW_WORKSPACE\sasview\src\sas\sasgui\perspectives\fitting\basepage.py", line 1955, in _on_select_model_helper
    if form_factor is None or not form_factor.is_form_factor:

AttributeError: class Model has no attribute 'is_form_factor'

Migrated from http://trac.sasview.org/ticket/744
```json
{
    "status": "closed",
    "changetime": "2016-10-09T15:16:02",
    "_ts": "2016-10-09 15:16:02.627269+00:00",
    "description": "Old style python custom model don't load. It was fixed before but apparently the issue reoccurred. It doesn't work either on windows or mac (regardless opencl or not).\n\nTraceback (most recent call last):\n  File \"C:\\Users\\wojtek\\SASVIEW_WORKSPACE\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\fitpage.py\", line 1179, in _on_select_model\n    self._on_select_model_helper()\n  File \"C:\\Users\\wojtek\\SASVIEW_WORKSPACE\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\basepage.py\", line 1955, in _on_select_model_helper\n    if form_factor is None or not form_factor.is_form_factor:\n\nAttributeError: class Model has no attribute 'is_form_factor'",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-09T14:57:35",
    "component": "SasView",
    "summary": "Old-style custom models don't load",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/09 15:15:56`: **wojciech** commented:

Solved by Matthieu in commit [https://github.com/SasView/sasmodels/commit/ed10b575284d50e5f99b3b93b89f0ec5edb5a6d5 ed10b575284d50e5f99b3b93b89f0ec5edb5a6d5]

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/09 15:16:02`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "new" to "closed"
