### ISSUE TITLE
Load Plugin error (Trac #863)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#951]
Load Plugin is used to force an update of plugin models that may have changed but somehow not triggered an auto update.  This works fine if the category at the time is **not** Plugin Model.  However if it is "Plugin Model" and a plugin is selected on the fit page, load will clear the model dropdown box, but does not clear the rest of the model GUI stuff on the fit page.  If the user then tries to change a parameter and run the model (e.g. by hitting return) throws an error. If the user then goes to the model selection drop down and reselects the model all is well again. 

```text
2017-02-26 11:30:47 : Traceback (most recent call last):
File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
    self.compute(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'pow'

2017-02-26 11:30:47 : Traceback (most recent call last):
File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
    self.compute(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'pow'
```

Interesting factoid: there are 4 types of models: new style (e.g. copied from the built in), created using simple model editor (essentially new style), old style plugins, and the sum/multiply models which remain a mix of styles.  This last type in fact seems to be quite happy even when the drop down is cleared - i.e. it does not throw the error and in fact continues to work fine when parameters are changed as if it is loaded at some deeper level? maybe deep copy issue?

Possible solutions:
1.  Rather than reset the selected model of Plugin Model, the code could reload whatever model had been selected and keep that model in the dropdown.
2. Finish the reset operation.  Basically this is behaving similarly to changing category which clears the model selection box AND clears all the model GUI elements on the page.  So just finish the job and clear out all those elements. 
 

Migrated from http://trac.sasview.org/ticket/863
```json
{
    "status": "closed",
    "changetime": "2017-03-08T03:35:33",
    "_ts": "2017-03-08 03:35:33.040361+00:00",
    "description": "Load Plugin is used to force an update of plugin models that may have changed but somehow not triggered an auto update.  This works fine if the category at the time is **not** Plugin Model.  However if it is \"Plugin Model\" and a plugin is selected on the fit page, load will clear the model dropdown box, but does not clear the rest of the model GUI stuff on the fit page.  If the user then tries to change a parameter and run the model (e.g. by hitting return) throws an error. If the user then goes to the model selection drop down and reselects the model all is well again. \n\n\n{{{\n2017-02-26 11:30:47 : Traceback (most recent call last):\nFile \"C:\\Users\\Paul\\git\\sasview_new\\src\\sas\\sascalc\\data_util\\calcthread.py\", line 268, in _run\n    self.compute(*args, **kwargs)\nAttributeError: 'NoneType' object has no attribute 'pow'\n\n2017-02-26 11:30:47 : Traceback (most recent call last):\nFile \"C:\\Users\\Paul\\git\\sasview_new\\src\\sas\\sascalc\\data_util\\calcthread.py\", line 268, in _run\n    self.compute(*args, **kwargs)\nAttributeError: 'NoneType' object has no attribute 'pow'\n}}}\n\nInteresting factoid: there are 4 types of models: new style (e.g. copied from the built in), created using simple model editor (essentially new style), old style plugins, and the sum/multiply models which remain a mix of styles.  This last type in fact seems to be quite happy even when the drop down is cleared - i.e. it does not throw the error and in fact continues to work fine when parameters are changed as if it is loaded at some deeper level? maybe deep copy issue?\n\nPossible solutions:\n1.  Rather than reset the selected model of Plugin Model, the code could reload whatever model had been selected and keep that model in the dropdown.\n2. Finish the reset operation.  Basically this is behaving similarly to changing category which clears the model selection box AND clears all the model GUI elements on the page.  So just finish the job and clear out all those elements. \n ",
    "reporter": "butler",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-26T16:46:55",
    "component": "SasView",
    "summary": "Load Plugin error",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/02/27 04:38:19`: **butler** changed description from:

> Load Plugin is used to force an update of plugin models that may have changed but somehow not triggered an auto update.  This works fine if the category at the time is **not** Plugin Model.  However if it is "Plugin Model" and a plugin is selected on the fit page, load will clear the model dropdown box, but does not clear the rest of the model GUI stuff on the fit page.  Strangely, if the model that had been chosen is a new style plugin and the user then tries to change a parameter and run the model everything behaves though the model dropdown remains blank (suggesting no model is currently "active" for that fit page.  However, doing the same thing with an old style plugin causes an error that throws a rather unhelpful error message suggesting a thread problem along with a more useful error that the parameter being modified does not exist.
> 
> {{{
> 2017-02-26 11:30:47 : Traceback (most recent call last):
> File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
>     self.compute(*args, **kwargs)
> AttributeError: 'NoneType' object has no attribute 'pow'
> 
> 2017-02-26 11:30:47 : Traceback (most recent call last):
> File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
>     self.compute(*args, **kwargs)
> AttributeError: 'NoneType' object has no attribute 'pow'
> }}}
> 
> Not sure why this does not also throw an error with new style models but if it is going to work the drop down should not be blank.
> 
> Possible solutions:
> 1.  Rather than reset the selected model of Plugin Model, the code could reload whatever model had been selected and keep that model in the dropdown.
> 2. Finish the reset operation.  Basically this is behaving similarly to changing category which clears the model selection box AND clears all the model GUI elements on the page.  So just finish the job and clear out all those elements. 
>  

to:

> Load Plugin is used to force an update of plugin models that may have changed but somehow not triggered an auto update.  This works fine if the category at the time is **not** Plugin Model.  However if it is "Plugin Model" and a plugin is selected on the fit page, load will clear the model dropdown box, but does not clear the rest of the model GUI stuff on the fit page.  If the user then tries to change a parameter and run the model (e.g. by hitting return) throws an error. If the user then goes to the model selection drop down and reselects the model all is well again. 
> 
> 
> {{{
> 2017-02-26 11:30:47 : Traceback (most recent call last):
> File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
>     self.compute(*args, **kwargs)
> AttributeError: 'NoneType' object has no attribute 'pow'
> 
> 2017-02-26 11:30:47 : Traceback (most recent call last):
> File "C:\Users\Paul\git\sasview_new\src\sas\sascalc\data_util\calcthread.py", line 268, in _run
>     self.compute(*args, **kwargs)
> AttributeError: 'NoneType' object has no attribute 'pow'
> }}}
> 
> Interesting factoid: there are 4 types of models: new style (e.g. copied from the built in), created using simple model editor (essentially new style), old style plugins, and the sum/multiply models which remain a mix of styles.  This last type in fact seems to be quite happy even when the drop down is cleared - i.e. it does not throw the error and in fact continues to work fine when parameters are changed as if it is loaded at some deeper level? maybe deep copy issue?
> 
> Possible solutions:
> 1.  Rather than reset the selected model of Plugin Model, the code could reload whatever model had been selected and keep that model in the dropdown.
> 2. Finish the reset operation.  Basically this is behaving similarly to changing category which clears the model selection box AND clears all the model GUI elements on the page.  So just finish the job and clear out all those elements. 
>

**Comment by butlerpd** [comment]
Trac update at `2017/03/08 03:35:33`: 
* **butler** commented:

This was a first observation of a deeper issue documented in #953.  Have moved this information there and thus closing this as a duplicate.


* **butler** changed resolution from "" to "duplicate"
* **butler** changed status from "new" to "closed"
